### ISSUE TITLE
Assertion `(flags & IMPLICIT_FLAGS) == 0' failed.

### ISSUE THREAD

**Issue by skidoo23** [MusicPlayerDaemon/MPD#1020]
### Describe the bug
Assertion fails when client connects to MPD. Does not matter if network or local socket.

## Expected Behavior
Normal operation.

## Actual Behavior
MPD exits.

## Version

Music Player Daemon 0.23~git (v0.22.3-161-g9d6b5e2ba)

## Log

(...)
client: [0] opened from 192.168.24.110:51503
client: [1] opened from 192.168.24.110:51504
client: [1] process command "channels"
client: [1] command returned 0
client: [1] process command "idle"
client: [1] command returned 1
client: [0] process command "replay_gain_mode off"
client: [0] command returned 0
client: [0] process command "stats"
client: [0] command returned 0
client: [0] process command "lsinfo "mpd-client://cantata/2.3.2""
exception: Unsupported URI scheme
client: [0] command returned 3
client: [0] process command "status"
mpd: ../src/event/SocketEvent.cxx:63: bool SocketEvent::Schedule(unsigned int): Assertion `(flags & IMPLICIT_FLAGS) == 0' failed.
(...)

**Comment by MaxKellermann** [comment]
Can't reproduce - I can connect/disconnect/reconnect just fine with clients.
Backtrace?

**Comment by skidoo23** [comment]
Yes. Need to recompile.

**Comment by skidoo23** [comment]
```
$ meson . output --buildtype=debug -Db_ndebug=false --reconfigure
$ ninja -C output
# ninja -C output install

mpd.conf

bind_to_address                 "any"
bind_to_address                 "/run/mpd/socket"

# gdb --args mpd --stderr --no-daemon --verbose
GNU gdb (Debian 10.1-1+b1) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mpd...
(gdb) run
Starting program: /usr/local/bin/mpd --stderr --no-daemon --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
config_file: loading file /etc/mpd.conf
path: SetFSCharset: fs charset is:
libsamplerate: libsamplerate converter 'Medium Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.7
opus: libopus 1.3.1
sndfile: libsndfile-1.0.28
simple_db: reading DB
curl: version 7.72.0
curl: with GnuTLS/3.6.15
[New Thread 0x7fffe91bf700 (LWP 13562)]
[New Thread 0x7fffe89be700 (LWP 13563)]
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Client changed to state 2
avahi: Client is RUNNING
avahi: Registering service _mpd._tcp/Music Player Daemon @ jukebox
avahi: Service group changed to state 0
avahi: Service group is UNCOMMITED
state_file: Loading state file /var/lib/mpd/state
avahi: Service group changed to state 1
avahi: Service group is REGISTERING
avahi: Service group changed to state 2
avahi: Service 'Music Player Daemon @ jukebox' successfully established.
client: [0] opened from 192.168.24.110:52005
client: [1] opened from 192.168.24.110:52006
client: [1] process command "channels"
client: [1] command returned 0
client: [1] process command "idle"
client: [1] command returned 1
client: [0] process command "replay_gain_mode off"
client: [0] command returned 0
client: [0] process command "stats"
client: [0] command returned 0
client: [0] process command "lsinfo "mpd-client://cantata/2.3.2""
exception: Unsupported URI scheme
client: [0] command returned 3
client: [0] process command "status"
mpd: ../src/event/SocketEvent.cxx:63: bool SocketEvent::Schedule(unsigned int): Assertion `(flags & IMPLICIT_FLAGS) == 0' failed.
client: [0] command returned 0
client: [0] process command "playlistinfo"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "stats"
client: [0] command returned 0
client: [0] process command "urlhandlers"
client: [0] command returned 0
client: [0] process command "tagtypes"
client: [0] command returned 0
client: [0] process command "commands"
client: [0] command returned 0
client: [0] process command "playlistinfo"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "lsinfo"
client: [0] command returned 0

Thread 3 "rtio" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe89be700 (LWP 13563)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff34e8537 in __GI_abort () at abort.c:79
#2  0x00007ffff34e840f in __assert_fail_base
    (fmt=0x7ffff3651108 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x5555556e0de2 "(flags & IMPLICIT_FLAGS) == 0", file=0x5555556e0da5 "../src/event/SocketEvent.cxx", line=63, function=<optimized out>) at assert.c:92
#3  0x00007ffff34f75c2 in __GI___assert_fail
    (assertion=0x5555556e0de2 "(flags & IMPLICIT_FLAGS) == 0", file=0x5555556e0da5 "../src/event/SocketEvent.cxx", line=63, function=0x5555556e0d50 "bool SocketEvent::Schedule(unsigned int)") at assert.c:101
#4  0x00005555555ec0fb in SocketEvent::Schedule(unsigned int)
    (this=0x7fffe4000cf0, flags=41) at ../src/event/SocketEvent.cxx:63
#5  0x00005555556c0c28 in MultiSocketMonitor::SingleFD::Schedule(unsigned int)
    (this=0x7fffe4000ce8, events=41) at ../src/event/MultiSocketMonitor.hxx:75
#6  0x00005555556c0453 in MultiSocketMonitor::AddSocket(SocketDescriptor, unsigned int) (this=0x555556071300, fd=..., events=41)
    at ../src/event/MultiSocketMonitor.cxx:56
#7  0x00005555556c0652 in MultiSocketMonitor::ReplaceSocketList(pollfd*, unsigned int) (this=0x555556071300, pfds=0x7fffe4000c10, n=1)
    at ../src/event/MultiSocketMonitor.cxx:105
#8  0x00005555556121fa in AlsaNonBlockMixer::PrepareSockets(MultiSocketMonitor&, _snd_mixer*) (this=0x5555560713b8, m=..., mixer=0x55555a89d3b0)
    at ../src/lib/alsa/NonBlock.cxx:93
--Type <RET> for more, q to quit, c to continue without paging--c
#9  0x00005555556d0b6d in AlsaMixerMonitor::PrepareSockets() (this=0x555556071300) at ../src/mixer/plugins/AlsaMixerPlugin.cxx:110
#10 0x00005555556c067f in MultiSocketMonitor::Prepare() (this=0x555556071300) at ../src/event/MultiSocketMonitor.cxx:113
#11 0x00005555556c079d in MultiSocketMonitor::OnIdle() (this=0x555556071300) at ../src/event/MultiSocketMonitor.cxx:148
#12 0x00005555556c1323 in BindMethodDetail::BindMethodWrapperGenerator2<MultiSocketMonitor, true, void (MultiSocketMonitor::*)() noexcept, &MultiSocketMonitor::OnIdle, void>::Invoke(void*) (_instance=0x555556071300) at ../src/util/BindMethod.hxx:189
#13 0x00005555555ebab0 in BoundMethod<void () noexcept>::operator()() const (this=0x555556071320) at ../src/util/BindMethod.hxx:91
#14 0x00005555555f1a82 in DeferEvent::Run() (this=0x555556071308) at ../src/event/DeferEvent.hxx:76
#15 0x00005555555f0cc6 in operator()(DeferEvent*) const (__closure=0x7fffe89bd12f, e=0x555556071308) at ../src/event/Loop.cxx:223
#16 0x00005555555f14a1 in IntrusiveList<DeferEvent>::pop_front_and_dispose<EventLoop::RunOneIdle()::<lambda(DeferEvent*)> >(struct {...} &&) (this=0x7fffffffe6f8, disposer=...) at ../src/util/IntrusiveList.hxx:204
#17 0x00005555555f0d08 in EventLoop::RunOneIdle() (this=0x7fffffffe688) at ../src/event/Loop.cxx:222
#18 0x00005555555f0f45 in EventLoop::Run() (this=0x7fffffffe688) at ../src/event/Loop.cxx:319
#19 0x00005555555f0205 in EventThread::Run() (this=0x7fffffffe688) at ../src/event/Thread.cxx:65
#20 0x00005555555a074e in BindMethodDetail::BindMethodWrapperGenerator2<EventThread, true, void (EventThread::*)() noexcept, &EventThread::Run, void>::Invoke(void*) (_instance=0x7fffffffe688) at ../src/util/BindMethod.hxx:189
#21 0x00005555555ebab0 in BoundMethod<void () noexcept>::operator()() const (this=0x7fffffffe788) at ../src/util/BindMethod.hxx:91
#22 0x00005555555f66d0 in Thread::Run() (this=0x7fffffffe788) at ../src/thread/Thread.cxx:63
#23 0x00005555555f66b1 in Thread::ThreadProc(void*) (ctx=0x7fffffffe788) at ../src/thread/Thread.cxx:92
#24 0x00007ffff3690ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#25 0x00007ffff35c0d4f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by MaxKellermann** [comment]
Your bug report was misleading. This has nothing to do with client connects. This is an ALSA plugin bug which is revealed by a recent change.
