### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [MusicPlayerDaemon/MPD#1042]
```
...
2021-01-08 13:14:14,127 DEBUG: buildserver > [208/549] Compiling C++ object 'src/tag/b545a07@@GenParseName@exe/GenParseName.cxx.o'.
2021-01-08 13:14:14,128 DEBUG: buildserver > FAILED: src/tag/b545a07@@GenParseName@exe/GenParseName.cxx.o
2021-01-08 13:14:14,128 DEBUG: buildserver > c++ -Isrc/tag/b545a07@@GenParseName@exe -Isrc/tag -I../../src/tag -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -std=c++17  -MD -MQ 'src/tag/b545a07@@GenParseName@exe/GenParseName.cxx.o' -MF 'src/tag/b545a07@@GenParseName@exe/GenParseName.cxx.o.d' -o 'src/tag/b545a07@@GenParseName@exe/GenParseName.cxx.o' -c ../../src/tag/GenParseName.cxx
2021-01-08 13:14:14,129 DEBUG: buildserver > ../../src/tag/GenParseName.cxx:24:23: fatal error: string_view: No such file or directory
2021-01-08 13:14:14,129 DEBUG: buildserver >  #include <string_view>
2021-01-08 13:14:14,129 DEBUG: buildserver >                        ^
2021-01-08 13:14:14,130 DEBUG: buildserver > compilation terminated.
2021-01-08 13:14:14,130 DEBUG: buildserver > [209/549] Compiling C++ object 'src/pcm/e54d52f@@pcm@sta/ConfiguredResampler.cxx.o'.
2021-01-08 13:14:14,131 DEBUG: buildserver > [210/549] Compiling C++ object 'src/input/8603e95@@input_api@sta/InputPlugin.cxx.o'.
2021-01-08 13:14:14,131 DEBUG: buildserver > [211/549] Compiling C++ object 'src/db/59acb73@@db_glue@sta/DatabasePlaylist.cxx.o'.
2021-01-08 13:14:14,132 DEBUG: buildserver > [212/549] Compiling C++ object 'src/db/59acb73@@db_glue@sta/update_InotifyQueue.cxx.o'.
2021-01-08 13:14:14,132 DEBUG: buildserver > [213/549] Compiling C++ object 'src/input/8603e95@@input_api@sta/ProxyInputStream.cxx.o'.
2021-01-08 13:14:14,133 DEBUG: buildserver > [214/549] Compiling C++ object 'src/db/59acb73@@db_glue@sta/DatabaseQueue.cxx.o'.
2021-01-08 13:14:14,133 DEBUG: buildserver > [215/549] Generating classes.jar with a custom command.
2021-01-08 13:14:14,133 DEBUG: buildserver > ninja: build stopped: subcommand failed.
2021-01-08 13:14:14,134 DEBUG: buildserver > download https://www.musicpd.org/download/libmpdclient/2/libmpdclient-2.19.tar.xz
2021-01-08 13:14:14,134 DEBUG: buildserver > download http://downloads.xiph.org/releases/ogg/libogg-1.3.4.tar.xz
2021-01-08 13:14:14,135 DEBUG: buildserver > download http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.7.tar.xz
2021-01-08 13:14:14,135 DEBUG: buildserver > download https://archive.mozilla.org/pub/opus/opus-1.3.1.tar.gz
2021-01-08 13:14:14,135 DEBUG: buildserver > download http://downloads.xiph.org/releases/flac/flac-1.3.3.tar.xz
2021-01-08 13:14:14,136 DEBUG: buildserver > download ftp://ftp.mars.org/pub/mpeg/libid3tag-0.15.1b.tar.gz
2021-01-08 13:14:14,136 DEBUG: buildserver > download https://downloads.sourceforge.net/modplug-xmms/libmodplug/0.8.9.0/libmodplug-0.8.9.0.tar.gz
2021-01-08 13:14:14,137 DEBUG: buildserver > download https://codeload.github.com/Mindwerks/wildmidi/tar.gz/wildmidi-0.4.3
2021-01-08 13:14:14,137 DEBUG: buildserver > download https://bitbucket.org/mpyne/game-music-emu/downloads/game-music-emu-0.6.3.tar.xz
2021-01-08 13:14:14,138 DEBUG: buildserver > download http://ffmpeg.org/releases/ffmpeg-4.3.1.tar.xz
2021-01-08 13:14:14,138 DEBUG: buildserver > download http://curl.haxx.se/download/curl-7.73.0.tar.xz
2021-01-08 13:14:14,138 DEBUG: buildserver > download https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.bz2
2021-01-08 13:14:14,139 DEBUG: buildserver > download https://github.com/sahlberg/libnfs/archive/libnfs-4.0.0.tar.gz
2021-01-08 13:14:14,139 DEBUG: buildserver > download https://dl.bintray.com/boostorg/release/1.74.0/source/boost_1_74_0.tar.bz2
2021-01-08 13:14:14,140 DEBUG: buildserver > Traceback (most recent call last):
2021-01-08 13:14:14,140 DEBUG: buildserver >   File "../../android/build.py", line 201, in <module>
2021-01-08 13:14:14,141 DEBUG: buildserver >     subprocess.check_call(['/usr/bin/ninja'], env=toolchain.env)
2021-01-08 13:14:14,141 DEBUG: buildserver >   File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
2021-01-08 13:14:14,141 DEBUG: buildserver >     raise CalledProcessError(retcode, cmd)
2021-01-08 13:14:14,142 DEBUG: buildserver > subprocess.CalledProcessError: Command '['/usr/bin/ninja']' returned non-zero exit status 1
2021-01-08 13:14:14,142 DEBUG: buildserver > ==== detail end ====
```
...what am I missing? 
This is the recipe:
```
  - versionName: 0.22.1
    versionCode: 51
    commit: v0.22.1
    sudo:
      - apt-get update || apt-get update
      - apt-get install -y libc++-7-dev
      - apt-get install -y g++ imagemagick-6.q16 meson -t stretch-backports
    output: output/android/android/apk/mpd-unsigned.apk
    prebuild: mkdir -p output/android/android/classes/
    scandelete:
      - src/haiku/
    build:
      - cd output/android/
      - ../../android/build.py $$SDK$$ $$NDK$$ arm64-v8a
      - meson configure
      - ninja android/apk/mpd-unsigned.apk
    ndk: r20b
```
...we are on Debian Stretch so maybe that's the issue?

**Comment by MaxKellermann** [comment]
Your toolchain is not C++17 compliant, and thus is not capable of building MPD.
