### ISSUE TITLE
Help compiling mpd for windows

### ISSUE THREAD

**Issue by ansanes** [MusicPlayerDaemon/MPD#1112]
While trying to do a cross-compile mpd build for windows 64 on ubuntu 20 I'm getting this error:
```
sudo ../../win32/build.py --64
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-w64-mingw32-strip... /usr/bin/x86_64-w64-mingw32-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for x86_64-w64-mingw32-gcc... /usr/bin/x86_64-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/x86_64-w64-mingw32-gcc accepts -g... yes
checking for /usr/bin/x86_64-w64-mingw32-gcc option to accept ISO C89... none needed
checking whether /usr/bin/x86_64-w64-mingw32-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of /usr/bin/x86_64-w64-mingw32-gcc... gcc3
checking whether we are using the GNU C++ compiler... no
checking whether /usr/bin/x86_64-w64-mingw32-g++ accepts -g... no
checking dependency style of /usr/bin/x86_64-w64-mingw32-g++... none
checking how to run the C++ preprocessor... /lib/cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... no
checking for sys/types.h... no
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking whether byte ordering is bigendian... unknown
configure: error: unknown endianness
 presetting ac_cv_c_bigendian=no (or yes) will help
Traceback (most recent call last):
  File "../../win32/build.py", line 120, in <module>
    x.build(toolchain)
  File "/home/ansanes/Desktop/mpd-0.22.6/python/build/autotools.py", line 59, in build
    build = self.configure(toolchain)
  File "/home/ansanes/Desktop/mpd-0.22.6/python/build/autotools.py", line 55, in configure
    subprocess.check_call(configure, cwd=build, env=toolchain.env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ansanes/Desktop/mpd-0.22.6/output/win64/lib/src/libmodplug-0.8.9.0/configure', 'CC=/usr/bin/x86_64-w64-mingw32-gcc', 'CXX=/usr/bin/x86_64-w64-mingw32-g++', 'CFLAGS=-O2 -g', 'CXXFLAGS=-O2 -g', 'CPPFLAGS=-isystem /home/ansanes/Desktop/mpd-0.22.6/output/win64/lib/x86_64-w64-mingw32/root/include -DWINVER=0x0600 -D_WIN32_WINNT=0x0600 -D_FORTIFY_SOURCE=0 ', 'LDFLAGS=-L/home/ansanes/Desktop/mpd-0.22.6/output/win64/lib/x86_64-w64-mingw32/root/lib -static-libstdc++ -static-libgcc ', 'LIBS= ', 'AR=/usr/bin/x86_64-w64-mingw32-ar', 'RANLIB=/usr/bin/x86_64-w64-mingw32-ranlib', 'STRIP=/usr/bin/x86_64-w64-mingw32-strip', '--host=x86_64-w64-mingw32', '--prefix=/home/ansanes/Desktop/mpd-0.22.6/output/win64/lib/x86_64-w64-mingw32/root', '--enable-silent-rules', '--disable-shared', '--enable-static']' returned non-zero exit status 1
```

Is there any tool/dependency that I'm missing?

**Comment by MaxKellermann** [comment]
Don't `sudo`! Compiling MPD doesn't require superuser privileges. (That has nothing to do with your problem, though.)

This is about a libmodplug's failure, so not strictly a MPD problem. Look at its `config.log` (in `output/win64/lib/x86_64-w64-mingw32/build/libmodplug-0.8.9.0/`) for details.

**Comment by ansanes** [comment]
Thanks. After installing the required dependencies and the process compiling a lot of the dependencies I'm getting this message:
```
Build started at 2021-02-25T13:43:07.108831
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /home/ansanes/Desktop/mpd-0.22.6
Build dir: /home/ansanes/Desktop/mpd-0.22.6/output/win64
Build type: cross build

meson_options.txt:1:0: ERROR: Unknown type feature.
```

**Comment by MaxKellermann** [comment]
What were the required dependencies?
Certainly one dependency is missing: Meson 0.49. Your version is 0.45. See https://www.musicpd.org/doc/html/user.html#compiling-from-source

**Comment by ansanes** [comment]
I've had to install multiple dependencies during the process x86_64-w64-mingw32-g++, quilt, cmake. I've also managed to install meson 0.49 using pip but now it's complaining about ninja.

> 
> 
> What were the required dependencies?
> Certainly one dependency is missing: Meson 0.49. Your version is 0.45. See https://www.musicpd.org/doc/html/user.html#compiling-from-source

**Comment by MaxKellermann** [comment]
Of course, you ignored a documented requirement again:
> a C++17 compiler (e.g. GCC 8 or clang 5)

(from https://www.musicpd.org/doc/html/user.html#compiling-from-source)

you have GCC 7, which is not C++17 compliant.

**Comment by ansanes** [comment]
Thanks. I'm having a lot of trouble setting up my toolchain to be able to cross compile mpd. I wish there was a guide to do this (maybe I'll create one if I succed). 

Before continuing I'd like to know if after compiling I will get all the output plugins avaiable, specifically the jack plugin as this is the one I'm most interested in. ¿Do you know how reliable is it on windows? ¿Is there any place where I can download a prebuild windows binary with the jack plugin?


> 
> 
> Of course, you ignored a documented requirement again:
> 
> > a C++17 compiler (e.g. GCC 8 or clang 5)
> 
> (from https://www.musicpd.org/doc/html/user.html#compiling-from-source)
> 
> you have GCC 7, which is not C++17 compliant.
