### ISSUE TITLE
Error when build with documentation enabled: RuntimeError: File 'doc/mpd.1' could not be found

### ISSUE THREAD

**Issue by PRESFIL** [MusicPlayerDaemon/MPD#1183]
### Describe the bug

I am trying to compile the -git version of `mpd` with `pikaur` from the AUR. There is no man page file in the final stage of building the package:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 134, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 719, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 511, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 614, in install_targets
    raise RuntimeError(f'File {t.fname!r} could not be found')
RuntimeError: File 'doc/mpd.1' could not be found
FAILED: meson-install
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

## Expected Behavior

The package assembly should complete correctly.

## Actual Behavior

The build stops because of a not found file or mixed paths in the project settings.

## Version

`mpd` sources version: latest commit from `master` branch. See on [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mpd-git&id=1d36fa91754923ea3a6f62245b1ed8177576255d#n35).
`pikaur` version: `v1.6.17.r12.g4df1a75`

## Log

<details>

Where $HOME is my home folder.

```
Installing mpd to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/bin
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/client.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/developer.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/index.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/mpd.1.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/mpd.conf.5.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/plugins.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/protocol.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/user.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/genindex.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/search.html to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/.buildinfo to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/objects.inv to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/searchindex.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_sources/client.rst.txt to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_sources
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_sources/developer.rst.txt to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_sources
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_sources/index.rst.txt to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_sources
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_sources/mpd.1.rst.txt to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_sources
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_sources/mpd.conf.5.rst.txt to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_sources
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_sources/plugins.rst.txt to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_sources
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_sources/protocol.rst.txt to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_sources
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_sources/user.rst.txt to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_sources
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/pygments.css to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/basic.css to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/doctools.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/documentation_options.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/file.png to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/jquery-3.5.1.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/jquery.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/language_data.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/minus.png to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/plus.png to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/searchtools.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/underscore-1.12.0.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/underscore.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/classic.css to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Installing $HOME/.cache/pikaur/build/mpd-git/src/mpd/build/doc/html/_static/sidebar.js to $HOME/.cache/pikaur/build/mpd-git/pkg/mpd-git/usr/share/doc/mpd/html/_static
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 134, in run
    return options.run_func(options)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 719, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 511, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/lib/python3.9/site-packages/mesonbuild/minstall.py", line 614, in install_targets
    raise RuntimeError(f'File {t.fname!r} could not be found')
RuntimeError: File 'doc/mpd.1' could not be found
FAILED: meson-install
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
```

</details>

**Comment by MaxKellermann** [comment]
Your log is incomplete. It doesn't show the sphinx call.
What is the latest MPD commit which doesn't have this problem?

**Comment by PRESFIL** [comment]
I don’t know why, but now everything is going correctly. Everything was put
together for commit 3668060. It looks like this is the same commit that caused
the problem, but it's okay now.

Apparently `sphinx` (or something) was updated a couple of days after I created
an issue.

**Comment by lfam** [comment]
In GNU Guix, we hit the same error with Sphinx 4.0.1.

It worked when trying 4.0.2; we upgraded to 4.0.3.

**Comment by MaxKellermann** [comment]
Thanks for the hint, @lfam - I have been using Sphinx 3.4.3 (Debian Bullseye, outdated before it's even released ...).
