### ISSUE TITLE
Segfault when using pipewire output

### ISSUE THREAD

**Issue by kartikynwa** [MusicPlayerDaemon/MPD#1376]
### Describe the bug

When changing songs, mpd eventually crashes when pipewire output is being used. I am using a client called [ashuffle](https://github.com/joshkunz/ashuffle) but I don't think ashuffle is the culprit. The crash does not happen when I am use the `pulse` output plugin.

Please let me know if I have missed any important information.

## Expected Behavior

mpd should not crash.

## Actual Behavior

mpd crashes when changing songs sooner or later.

## Version
```
Music Player Daemon 0.23.5 (0.23.5)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 tcp un
```

## Backtrace

```gdb
player: played "synced_music/Singles/U2 - Sometimes You Can't Make It On Your Own.mp3"

Thread 7 "pipewire Output" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f74b5505640 (LWP 31746)]
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:355
355     ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: No such file or directory.
(gdb) bt
#0  __memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:355
#1  0x00007f74b437c6b9 in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#2  0x00007f74b4389bb7 in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#3  0x00007f74b439cf31 in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#4  0x00007f74b438fb48 in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#5  0x00007f74b437d8da in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#6  0x00007f74be3c1576 in pw_impl_node_for_each_param () from /usr/lib/libpipewire-0.3.so.0
#7  0x00007f74be3e3cfc in ?? () from /usr/lib/libpipewire-0.3.so.0
#8  0x00007f74be3bcfab in ?? () from /usr/lib/libpipewire-0.3.so.0
#9  0x00007f74be3c53c9 in ?? () from /usr/lib/libpipewire-0.3.so.0
#10 0x00007f74b4383c9e in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#11 0x00007f74b43899ee in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#12 0x00007f74b43978ae in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#13 0x00007f74b439803e in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#14 0x00007f74b43832d5 in ?? () from /usr/lib64/spa-0.2/audioconvert/libspa-audioconvert.so
#15 0x00007f74b4c61d60 in ?? () from /usr/lib64/pipewire-0.3/libpipewire-module-client-node.so
#16 0x00007f74b4c70b75 in ?? () from /usr/lib64/pipewire-0.3/libpipewire-module-client-node.so
#17 0x00007f74b4ca8342 in ?? () from /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so
#18 0x00007f74b4ca8950 in ?? () from /usr/lib64/pipewire-0.3/libpipewire-module-protocol-native.so
#19 0x00007f74b811235b in ?? () from /usr/lib64/spa-0.2/support/libspa-support.so
#20 0x00007f74be3e3352 in ?? () from /usr/lib/libpipewire-0.3.so.0
#21 0x00007f74bd440eae in start_thread (arg=0x7f74b5505640) at pthread_create.c:463
#22 0x00007f74bd3702ff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by MaxKellermann** [comment]
This crashes is inside libpipewire (one of its plugins), inside libpipewire's own thread, outside of MPD's control. Until someone demonstrates otherwise, I assume this bug has nothing to do with MPD.
