### ISSUE TITLE
UBSAN/ASAN enabled MPD build reports

### ISSUE THREAD

**Issue by dgcampea** [MusicPlayerDaemon/MPD#1490]
## Description
Debug logs from UBSAN/ASAN enabled MPD build.

## Build info
Based on rpmfusion src-rpm for `mpd 0.23.6`.
Meson options: `-Dc_args="-fno-omit-frame-pointer"  -Db_sanitize=address,undefined -Dqobuz=disabled -Dsoundcloud=disabled -Dhtml_manual=false`
RPM spec changes:
```
# do not set _FORTIFY_SOURCE
%_preprocessor_defines  -Wp,-D_GLIBCXX_ASSERTIONS

(...)

# sanitizer deps
BuildRequires: libubsan
BuildRequires: libasan

(...)

# required for build to succeed
export LSAN_OPTIONS=verbosity=1:log_threads=1
%meson (...)
```

## Version
```
Music Player Daemon 0.23.6 (0.23.6)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## ASAN/UBSAN options
Passed via systemd override:
```
[Service]
Restart=always
RestartSec=5
Environment="UBSAN_OPTIONS=print_stacktrace=1,log_path=/tmp/mpd-ubsan.log"
Environment="ASAN_OPTIONS=detect_stack_use_after_return=1,check_initialization_order=1,strict_string_checks=1,log_path=/tmp/mpd-asan.log"
```

#### journalctl
```
server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
config: option 'dscp_class' on line 10 was not recognized
config: option 'dscp_class' on line 22 was not recognized
config: option 'dscp_class' on line 39 was not recognized
server_socket: bind to '0.0.0.0:6680' failed (continuing anyway, because binding to '[::]:6680' succeeded): Failed to bind socket: Address already in use
server_socket: bind to '0.0.0.0:6681' failed (continuing anyway, because binding to '[::]:6681' succeeded): Failed to bind socket: Address already in use
server_socket: bind to '0.0.0.0:6682' failed (continuing anyway, because binding to '[::]:6682' succeeded): Failed to bind socket: Address already in use
../src/decoder/plugins/FfmpegDecoderPlugin.cxx:387:30: runtime error: reference binding to null pointer of type 'struct AVDictionary'
    #0 0x5648f0967c5f in FfmpegParseMetaData ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:387
    #1 0x5648f0967c5f in FfmpegParseMetaData ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:397
    #2 0x5648f0967c5f in FfmpegParseMetaData ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:411
    #3 0x5648f0967c5f in FfmpegDecode ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:538
    #4 0x5648f096ac6e in ffmpeg_decode ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:612
    #5 0x5648f01c8822 in DecoderPlugin::StreamDecode(DecoderClient&, InputStream&) const ../src/decoder/DecoderPlugin.hxx:202
    #6 0x5648f01c8822 in decoder_stream_decode ../src/decoder/Thread.cxx:118
    #7 0x5648f01ef36f in TryDecoderFile ../src/decoder/Thread.cxx:344
    #8 0x5648f01ef36f in operator() ../src/decoder/Thread.cxx:425
    #9 0x5648f01ef36f in decoder_plugins_try<decoder_run_file(DecoderBridge&, char const*, Path)::<lambda(const DecoderPlugin&)> > ../src/decoder/DecoderList.hxx:72
    #10 0x5648f01ef36f in decoder_run_file ../src/decoder/Thread.cxx:423
    #11 0x5648f01ef36f in DecoderUnlockedRunUri ../src/decoder/Thread.cxx:443
    #12 0x5648f01ef36f in decoder_run_song ../src/decoder/Thread.cxx:505
    #13 0x5648f01ef36f in decoder_run ../src/decoder/Thread.cxx:546
    #14 0x5648f01f8f88 in DecoderControl::RunThread() ../src/decoder/Thread.cxx:571
    #15 0x5648f01f8f88 in BindMethodDetail::WrapperGenerator<void (DecoderControl::*)() noexcept, &DecoderControl::RunThread>::Invoke(void*) ../src/util/BindMethod.hxx:130
    #16 0x5648f04d4ab6 in BoundMethod<void () noexcept>::operator()() const ../src/util/BindMethod.hxx:78
    #17 0x5648f04d4ab6 in Thread::Run() ../src/thread/Thread.cxx:63
    #18 0x5648f04d4ab6 in Thread::ThreadProc(void*) ../src/thread/Thread.cxx:92
    #19 0x7f6dd11d5b19 in start_thread (/lib64/libc.so.6+0x8db19)
    #20 0x7f6dd125a64f in __GI___clone3 (/lib64/libc.so.6+0x11264f)
../src/decoder/plugins/FfmpegDecoderPlugin.cxx:396:38: runtime error: reference binding to null pointer of type 'struct AVDictionary'
    #0 0x5648f09677fc in FfmpegParseMetaData ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:396
    #1 0x5648f09677fc in FfmpegParseMetaData ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:411
    #2 0x5648f09677fc in FfmpegDecode ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:538
    #3 0x5648f096ac6e in ffmpeg_decode ../src/decoder/plugins/FfmpegDecoderPlugin.cxx:612
    #4 0x5648f01c8822 in DecoderPlugin::StreamDecode(DecoderClient&, InputStream&) const ../src/decoder/DecoderPlugin.hxx:202
    #5 0x5648f01c8822 in decoder_stream_decode ../src/decoder/Thread.cxx:118
    #6 0x5648f01ef36f in TryDecoderFile ../src/decoder/Thread.cxx:344
    #7 0x5648f01ef36f in operator() ../src/decoder/Thread.cxx:425
    #8 0x5648f01ef36f in decoder_plugins_try<decoder_run_file(DecoderBridge&, char const*, Path)::<lambda(const DecoderPlugin&)> > ../src/decoder/DecoderList.hxx:72
    #9 0x5648f01ef36f in decoder_run_file ../src/decoder/Thread.cxx:423
    #10 0x5648f01ef36f in DecoderUnlockedRunUri ../src/decoder/Thread.cxx:443
    #11 0x5648f01ef36f in decoder_run_song ../src/decoder/Thread.cxx:505
    #12 0x5648f01ef36f in decoder_run ../src/decoder/Thread.cxx:546
    #13 0x5648f01f8f88 in DecoderControl::RunThread() ../src/decoder/Thread.cxx:571
    #14 0x5648f01f8f88 in BindMethodDetail::WrapperGenerator<void (DecoderControl::*)() noexcept, &DecoderControl::RunThread>::Invoke(void*) ../src/util/BindMethod.hxx:130
    #15 0x5648f04d4ab6 in BoundMethod<void () noexcept>::operator()() const ../src/util/BindMethod.hxx:78
    #16 0x5648f04d4ab6 in Thread::Run() ../src/thread/Thread.cxx:63
    #17 0x5648f04d4ab6 in Thread::ThreadProc(void*) ../src/thread/Thread.cxx:92
    #18 0x7f6dd11d5b19 in start_thread (/lib64/libc.so.6+0x8db19)
    #19 0x7f6dd125a64f in __GI___clone3 (/lib64/libc.so.6+0x11264f)
```

### Log 2
```
/usr/include/c++/11/chrono:240:38: runtime error: signed integer overflow: -10188633600 * 1000000000 cannot be represented in type 'long int'
    #0 0x556e04cb1261 in std::chrono::duration<long, std::ratio<1l, 1000000000l> > std::chrono::__duration_cast_impl<std::chrono::duration<long, std::ratio<1l, 1000000000l> >, std::ratio<1000000000l, 1l>, long, false, true>::__cast<long, std::ratio<1l, 1l> >(std::chrono::duration<long, std::ratio<1l, 1l> > const&) /usr/include/c++/11/chrono:240
    #1 0x556e04cb1261 in std::enable_if<std::chrono::__is_duration<std::chrono::duration<long, std::ratio<1l, 1000000000l> > >::value, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >::type std::chrono::duration_cast<std::chrono::duration<long, std::ratio<1l, 1000000000l> >, long, std::ratio<1l, 1l> >(std::chrono::duration<long, std::ratio<1l, 1l> > const&) /usr/include/c++/11/chrono:276
    #2 0x556e04cb1261 in std::enable_if<std::chrono::__is_duration<std::chrono::duration<long, std::ratio<1l, 1000000000l> > >::value, std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > >::type std::chrono::time_point_cast<std::chrono::duration<long, std::ratio<1l, 1000000000l> >, std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1l> > >(std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long, std::ratio<1l, 1l> > > const&) /usr/include/c++/11/chrono:960
    #3 0x556e04cb1261 in std::chrono::_V2::system_clock::from_time_t(long) /usr/include/c++/11/chrono:1154
    #4 0x556e04cb1261 in TimeGm(tm&) ../src/time/Convert.cxx:104
    #5 0x556e0523c41c in ParseISO8601(char const*) ../src/time/ISO8601.cxx:226
    #6 0x556e0523c41c in ParseTimeStamp ../src/song/Filter.cxx:110
    #7 0x556e052777cf in SongFilter::ParseExpression(char const*&, bool) ../src/song/Filter.cxx:298
    #8 0x556e05285b5b in SongFilter::Parse(ConstBuffer<char const*>, bool) ../src/song/Filter.cxx:397
    #9 0x556e0496b36a in ParseDatabaseSelection ../src/command/DatabaseCommands.cxx:136
    #10 0x556e049a7cec in handle_searchaddpl(Client&, Request, Response&) ../src/command/DatabaseCommands.cxx:221
    #11 0x556e046971a3 in command_process(Client&, unsigned int, char*) ../src/command/AllCommands.cxx:432
    #12 0x556e047892fc in Client::ProcessLine(char*) ../src/client/Process.cxx:137
    #13 0x556e047892fc in Client::OnSocketInput(void*, unsigned long) ../src/client/Read.cxx:49
    #14 0x556e047892fc in Client::OnSocketInput(void*, unsigned long) ../src/client/Read.cxx:29
    #15 0x556e04aa15e2 in BufferedSocket::ResumeInput() ../src/event/BufferedSocket.cxx:76
    #16 0x556e04aa15e2 in BufferedSocket::OnSocketReady(unsigned int) ../src/event/BufferedSocket.cxx:113
    #17 0x556e04762b2b in BindMethodDetail::WrapperGenerator<void (BufferedSocket::*)(unsigned int) noexcept, &BufferedSocket::OnSocketReady>::Invoke(void*, unsigned int) ../src/util/BindMethod.hxx:130
    #18 0x556e04a6a078 in BoundMethod<void (unsigned int) noexcept>::operator()(unsigned int) const ../src/util/BindMethod.hxx:78
    #19 0x556e04a6a078 in SocketEvent::Dispatch() ../src/event/SocketEvent.cxx:121
    #20 0x556e04a6a078 in EventLoop::Run() ../src/event/Loop.cxx:362
    #21 0x556e0465a211 in MainConfigured ../src/Main.cxx:576
    #22 0x556e04668fff in MainOrThrow ../src/Main.cxx:661
    #23 0x556e0460ff6e in mpd_main(int, char**) ../src/Main.cxx:667
    #24 0x556e0460ff6e in main ../src/Main.cxx:679
    #25 0x7f0d65d7a55f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
    #26 0x7f0d65d7a60b in __libc_start_main_alias_1 (/lib64/libc.so.6+0x2d60b)
    #27 0x556e04612204  (/usr/bin/mpd+0x1715204)
```

### Log 3 (ubsan.log)
```
=================================================================
==148819==ERROR: AddressSanitizer: SEGV on unknown address 0x7f1fb3a36a28 (pc 0x7f1fb3a36a28 bp 0x000000000001 sp 0x7f1fbd4d3348 T8)
==148819==The signal is caused by a READ memory access.
==148819==Hint: PC is at a non-executable region. Maybe a wild jump?
    #0 0x7f1fb3a36a28  (<unknown module>)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
Thread T8 created by T5 here:
    #0 0x7f1fe50cb866 in pthread_create (/lib64/libasan.so.6+0x56866)
    #1 0x7f1fe25d16db in pw_thread_loop_start (/lib64/libpipewire-0.3.so.0+0x876db)
    #2 0x561e4d1f5e54 in FilteredAudioOutput::Enable() ../src/output/Filtered.cxx:60
    #3 0x561e4d1f5e54 in AudioOutputControl::InternalEnable() ../src/output/Thread.cxx:100
    #4 0x561e4d240472 in AudioOutputControl::Task() ../src/output/Thread.cxx:457
    #5 0x561e4d240472 in BindMethodDetail::WrapperGenerator<void (AudioOutputControl::*)() noexcept, &AudioOutputControl::Task>::Invoke(void*) ../src/util/BindMethod.hxx:130
    #6 0x561e4cf86ab6 in BoundMethod<void () noexcept>::operator()() const ../src/util/BindMethod.hxx:78
    #7 0x561e4cf86ab6 in Thread::Run() ../src/thread/Thread.cxx:63
    #8 0x561e4cf86ab6 in Thread::ThreadProc(void*) ../src/thread/Thread.cxx:92
    #9 0x7f1fdfaabb19 in start_thread (/lib64/libc.so.6+0x8db19)

Thread T5 created by T3 here:
    #0 0x7f1fe50cb866 in pthread_create (/lib64/libasan.so.6+0x56866)
    #1 0x561e4cfd6bbe in Thread::Start() ../src/thread/Thread.cxx:37
    #2 0x561e4d1f7fde in AudioOutputControl::StartThread() ../src/output/Thread.cxx:555
    #3 0x561e4d1f92aa in AudioOutputControl::EnableAsync() ../src/output/Control.cxx:210
    #4 0x561e4d1f92aa in AudioOutputControl::EnableDisableAsync() ../src/output/Control.cxx:243
    #5 0x561e4d1f92aa in AudioOutputControl::LockEnableDisableAsync() ../src/output/Control.hxx:409
    #6 0x561e4d1f92aa in MultipleOutputs::EnableDisable() ../src/output/MultipleOutputs.cxx:150
    #7 0x561e4cdbcb28 in Player::ProcessCommand(std::unique_lock<std::mutex>&) ../src/player/Thread.cxx:711
    #8 0x561e4cdd9cce in Player::Run() ../src/player/Thread.cxx:1005
    #9 0x561e4cdd9cce in do_play ../src/player/Thread.cxx:1158
    #10 0x561e4cdd9cce in PlayerControl::RunThread() ../src/player/Thread.cxx:1184
    #11 0x561e4cf86ab6 in BoundMethod<void () noexcept>::operator()() const ../src/util/BindMethod.hxx:78
    #12 0x561e4cf86ab6 in Thread::Run() ../src/thread/Thread.cxx:63
    #13 0x561e4cf86ab6 in Thread::ThreadProc(void*) ../src/thread/Thread.cxx:92
    #14 0x7f1fdfaabb19 in start_thread (/lib64/libc.so.6+0x8db19)

Thread T3 created by T0 here:
    #0 0x7f1fe50cb866 in pthread_create (/lib64/libasan.so.6+0x56866)
    #1 0x561e4cfd6bbe in Thread::Start() ../src/thread/Thread.cxx:37
    #2 0x561e4ce50b9d in PlayerControl::LockSeek(std::unique_ptr<DetachedSong, std::default_delete<DetachedSong> >, SongTime) ../src/player/Control.cxx:293
    #3 0x561e4ce50b9d in playlist::SeekSongOrder(PlayerControl&, unsigned int, SongTime) ../src/queue/PlaylistControl.cxx:231
    #4 0x561e4cb9ec2e in playlist_state_restore(StateFileConfig const&, char const*, LineReader&, SongLoader const&, playlist&, PlayerControl&) ../src/queue/PlaylistState.cxx:208
    #5 0x561e4cb9ec2e in StateFile::Read() ../src/StateFile.cxx:130
    #6 0x561e4cb9ec2e in glue_state_file_init ../src/Main.cxx:287
    #7 0x561e4cbb5151 in MainConfigured ../src/Main.cxx:531
    #8 0x561e4cbc4fff in MainOrThrow ../src/Main.cxx:661
    #9 0x561e4cb6bf6e in mpd_main(int, char**) ../src/Main.cxx:667
    #10 0x561e4cb6bf6e in main ../src/Main.cxx:679
    #11 0x7f1fdfa4b55f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)

==148819==ABORTING
```

### Log 4
```
../src/tag/ApeLoader.cxx:76:25: runtime error: load of misaligned address 0x619000f316a2 for type 'const uint32_t', which requires 4 byte alignment
0x619000f316a2: note: pointer points here
 72 00  30 31 02 00 00 00 00 00  00 00 43 75 65 5f 74 72  61 63 6b 30 32 5f 74 72  61 63 6b 6e 75 6d
              ^
    #0 0x558507682924 in tag_ape_scan(InputStream&, std::function<bool (unsigned long, char const*, StringView)> const&) ../src/tag/ApeLoader.cxx:76
    #1 0x558507d65876 in tag_ape_scan2(InputStream&, TagHandler&) ../src/tag/ApeTag.cxx:82
    #2 0x558507d65876 in ScanGenericTags(InputStream&, TagHandler&) [clone .isra.0] ../src/tag/Generic.cxx:35
    #3 0x558507d689b9 in ScanGenericTags(Path, TagHandler&) [clone .isra.0] ../src/tag/Generic.cxx:53
    #4 0x5585072de068 in ScanFileTagsWithGeneric(Path, TagBuilder&, AudioFormat*) ../src/TagFile.cxx:102
    #5 0x5585072e50a0 in Song::UpdateFile(Storage&) ../src/SongUpdate.cxx:90
    #6 0x5585079a9799 in UpdateWalk::UpdateSongFile2(Directory&, char const*, std::basic_string_view<char, std::char_traits<char> >, StorageFileInfo const&) ../src/db/update/UpdateSong.cxx:85
    #7 0x5585079a9799 in UpdateWalk::UpdateSongFile(Directory&, char const*, std::basic_string_view<char, std::char_traits<char> >, StorageFileInfo const&) ../src/db/update/UpdateSong.cxx:108
    #8 0x5585079a9799 in UpdateWalk::UpdateRegularFile(Directory&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:195
    #9 0x5585079a9799 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:208
    #10 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #11 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #12 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #13 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #14 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #15 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #16 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #17 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #18 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #19 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #20 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #21 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #22 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #23 0x5585079c70c9 in UpdateWalk::Walk(Directory&, char const*, bool) ../src/db/update/Walk.cxx:529
    #24 0x5585079c70c9 in UpdateService::Task() ../src/db/update/Service.cxx:122
    #25 0x5585073feab6 in BoundMethod<void () noexcept>::operator()() const ../src/util/BindMethod.hxx:78
    #26 0x5585073feab6 in Thread::Run() ../src/thread/Thread.cxx:63
    #27 0x5585073feab6 in Thread::ThreadProc(void*) ../src/thread/Thread.cxx:92
    #28 0x7f815f261b19 in start_thread (/lib64/libc.so.6+0x8db19)
    #29 0x7f815f2e664f in __GI___clone3 (/lib64/libc.so.6+0x11264f)
../src/tag/ApeLoader.cxx:79:33: runtime error: load of misaligned address 0x619000f316a6 for type 'const uint32_t', which requires 4 byte alignment
0x619000f316a6: note: pointer points here
 02 00 00 00 00 00  00 00 43 75 65 5f 74 72  61 63 6b 30 32 5f 74 72  61 63 6b 6e 75 6d 62 65  72 00
             ^
    #0 0x5585076828f1 in tag_ape_scan(InputStream&, std::function<bool (unsigned long, char const*, StringView)> const&) ../src/tag/ApeLoader.cxx:79
    #1 0x558507d65876 in tag_ape_scan2(InputStream&, TagHandler&) ../src/tag/ApeTag.cxx:82
    #2 0x558507d65876 in ScanGenericTags(InputStream&, TagHandler&) [clone .isra.0] ../src/tag/Generic.cxx:35
    #3 0x558507d689b9 in ScanGenericTags(Path, TagHandler&) [clone .isra.0] ../src/tag/Generic.cxx:53
    #4 0x5585072de068 in ScanFileTagsWithGeneric(Path, TagBuilder&, AudioFormat*) ../src/TagFile.cxx:102
    #5 0x5585072e50a0 in Song::UpdateFile(Storage&) ../src/SongUpdate.cxx:90
    #6 0x5585079a9799 in UpdateWalk::UpdateSongFile2(Directory&, char const*, std::basic_string_view<char, std::char_traits<char> >, StorageFileInfo const&) ../src/db/update/UpdateSong.cxx:85
    #7 0x5585079a9799 in UpdateWalk::UpdateSongFile(Directory&, char const*, std::basic_string_view<char, std::char_traits<char> >, StorageFileInfo const&) ../src/db/update/UpdateSong.cxx:108
    #8 0x5585079a9799 in UpdateWalk::UpdateRegularFile(Directory&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:195
    #9 0x5585079a9799 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:208
    #10 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #11 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #12 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #13 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #14 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #15 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #16 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #17 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #18 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #19 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #20 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #21 0x5585079a4af3 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) ../src/db/update/Walk.cxx:222
    #22 0x5585079c0399 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) ../src/db/update/Walk.cxx:385
    #23 0x5585079c70c9 in UpdateWalk::Walk(Directory&, char const*, bool) ../src/db/update/Walk.cxx:529
    #24 0x5585079c70c9 in UpdateService::Task() ../src/db/update/Service.cxx:122
    #25 0x5585073feab6 in BoundMethod<void () noexcept>::operator()() const ../src/util/BindMethod.hxx:78
    #26 0x5585073feab6 in Thread::Run() ../src/thread/Thread.cxx:63
    #27 0x5585073feab6 in Thread::ThreadProc(void*) ../src/thread/Thread.cxx:92
    #28 0x7f815f261b19 in start_thread (/lib64/libc.so.6+0x8db19)
    #29 0x7f815f2e664f in __GI___clone3 (/lib64/libc.so.6+0x11264f)
```

**Comment by MaxKellermann** [comment]
In log 2, what command was being processed?

**Comment by MaxKellermann** [comment]
Log 3 is a libpipewire bug

**Comment by dgcampea** [comment]
> In log 2, what command was being processed?

If I'm not mistaken, this sometimes happened with cue files

**Comment by MaxKellermann** [comment]
All problems have been fixed; except for 2, for which we don't exactly know how to reproduce, and 3, which is not a MPD bug.
