### ISSUE TITLE
Crash while updating db when encountering a MOV inside an ISO

### ISSUE THREAD

**Issue by cshapeshifter** [MusicPlayerDaemon/MPD#1556]
### Describe the bug
mpd crashes while updating. The crash is reproducible and happens when it encounters a specific .ISO file. For what it's worth, I don't actually need mpd to scan any ISO files.

## Version

```
Music Player Daemon 0.23.7 (0.23.7)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [openmpt] mptm mod s3m xm it 669 amf ams c67 dbm digi dmf dsm dtm far imf ice j2b m15 mdl med mms mt2 mtm nst okt plm psm pt36 ptm sfx sfx2 st26 stk stm stp ult wow gdm mo3 oxm umx xpk ppm mmcmp
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

## Configuration

```music_directory       "/mnt/nfs/enterprise/music/"

playlist_directory    "~/.config/mpd/playlists"
pid_file              "~/.config/mpd/pid"
state_file            "~/.config/mpd/state"
sticker_file          "~/.config/mpd/sticker.sql"
log_file              "~/.config/mpd/log"
log_level             "default"

audio_output {
  type "pulse"
  name "pulseaudio"
}

max_playlist_length   "65536"
```

## Log

Here's the relevant snippet:

```
( ... everything is normal ... )
mad: detected LAME version 3.92 ("LAME3.92 ")
mad: LAME peak found: 0
mad: encoder delay is 576, encoder padding is 2208
update: added Other/Band/2021/03.mp3
update: archive /mnt/nfs/enterprise/music/Other/RECORDING.ISO opened
update: adding archive file: AUTORUN.INF
update: adding archive file: DATA/RECORDING/AUDIO/RECORDING.MOV
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Format mov,mp4,m4a,3gp,3g2,mj2 probed with size=2048 and score=100
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'moov' parent:'root' sz: 1103 8 2610874
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'mvhd' parent:'moov' sz: 108 8 1095
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: time scale = 600
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'trak' parent:'moov' sz: 987 116 1095
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'tkhd' parent:'trak' sz: 92 8 979
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'edts' parent:'trak' sz: 36 100 979
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'elst' parent:'edts' sz: 28 8 28
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: track[0].edit_count = 1
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: duration=35505 time=0 rate=1.000000
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'mdia' parent:'trak' sz: 851 136 979
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'mdhd' parent:'mdia' sz: 32 8 843
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'hdlr' parent:'mdia' sz: 58 40 843
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: ctype=mhlr
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: stype=soun
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'minf' parent:'mdia' sz: 753 98 843
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'smhd' parent:'minf' sz: 16 8 745
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'hdlr' parent:'minf' sz: 57 24 745
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: ctype=dhlr
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: stype=alis
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'dinf' parent:'minf' sz: 36 81 745
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'dref' parent:'dinf' sz: 28 8 28
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unknown dref type 0x73696c61 size 12
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stbl' parent:'minf' sz: 636 117 745
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stsd' parent:'stbl' sz: 52 8 628
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: size=36 4CC=twos codec_type=1
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: audio channels 1
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: version =0, isom =0
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stts' parent:'stbl' sz: 24 60 628
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: track[0].stts.entries = 1
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: sample_count=1304809, sample_duration=1
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stsc' parent:'stbl' sz: 40 84 628
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: track[0].stsc.entries = 2
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stsz' parent:'stbl' sz: 20 124 628
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: sample_size = 2 sample_count = 1304809
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'stco' parent:'stbl' sz: 492 144 628
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: chunk count 1302
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, chunk 0, offset 4e8, dts 0, size 2048, duration 1024
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, chunk 0, offset ce8, dts 1024, size 2048, duration 1024
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, chunk 0, offset 14e8, dts 2048, size 2048, duration 1024
( ... many more lines like this ... )
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, chunk 118, offset 27c180, dts 1302092, size 2048, duration 1024
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, chunk 118, offset 27c980, dts 1303116, size 2048, duration 1024
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: AVIndex stream 0, chunk 118, offset 27d180, dts 1304140, size 1338, duration 669
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Processing st: 0, edit list 0 - media time: 0, duration: 1304809
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'free' parent:'root' sz: 137 1111 2610874
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: type:'mdat' parent:'root' sz: 2609634 1248 2610874
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: on_parse_exit_offset=1248
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Before avformat_find_stream_info() pos: 1248 bytes read:8192 seeks:0 nb_streams:1
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: stream 0, sample 0, dts 0
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: All info found
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: stream 0: start_time: 0 duration: 59.175
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: format: start_time: 0 duration: 59.175 (estimate from stream) bitrate=352 kb/s
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: After avformat_find_stream_info() pos: 3304 bytes read:8192 seeks:0 frames:1
/usr/include/c++/11.2.0/array:196: constexpr const value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) const [with _Tp = unsigned char; long unsigned int _Nm = 2048; std::array<_Tp, _Nm>::const_reference = const unsigned char&; std::array<_Tp, _Nm>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
( ... crash! ...)
```

## Core dump
```
Starting program: /usr/bin/mpd --stderr --no-daemon --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe236d640 (LWP 6933)]
[New Thread 0x7fffe1b6c640 (LWP 6934)]
[New Thread 0x7fffe136b640 (LWP 6936)]

Thread 4 "update" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe136b640 (LWP 6936)]
0x00007ffff2c8e36c in ?? () from /usr/lib/libc.so.6
#0  0x00007ffff2c8e36c in  () at /usr/lib/libc.so.6
#1  0x00007ffff2c3e838 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff2c28535 in abort () at /usr/lib/libc.so.6
#3  0x00005555555a02da in std::__replacement_assert(char const*, int, char const*, char const*)
    (__file=<optimized out>, __line=<optimized out>, __function=<optimized out>, __condition=<optimized out>) at /usr/include/c++/11.2.0/x86_64-pc-linux-gnu/bits/c++config.h:514
#4  0x000055555566272f in std::array<unsigned char, 2048ul>::operator[](unsigned long) const
    (this=<optimized out>, __n=<optimized out>) at /usr/include/c++/11.2.0/array:193
#5  std::array<unsigned char, 2048ul>::operator[](unsigned long) const
    (__n=2048, this=0x7fffcc019fb8) at /usr/include/c++/11.2.0/array:193
#6  Iso9660InputStream::BlockBuffer::Read() const (this=0x7fffcc019fa8)
    at ../mpd-0.23.7/src/archive/plugins/Iso9660ArchivePlugin.cxx:169
#7  Iso9660InputStream::Read(std::unique_lock<std::mutex>&, void*, unsigned long)
    (this=0x7fffcc019f20, ptr=0x7fffe1368900, read_size=32)
    at ../mpd-0.23.7/src/archive/plugins/Iso9660ArchivePlugin.cxx:296
#8  0x00005555555fdbe3 in InputStream::ReadFull(std::unique_lock<std::mutex>&, void*, unsigned long)
    (this=0x7fffcc019f20, lock=..., _ptr=0x7fffe1368900, _size=32)
    at ../mpd-0.23.7/src/input/InputStream.cxx:130
#9  0x00005555556010bf in tag_ape_scan(InputStream&, std::function<bool (unsigned long, char const*, StringView)> const&) (is=..., callback=...) at ../mpd-0.23.7/src/tag/ApeLoader.cxx:50
#10 0x00005555556783a8 in tag_ape_scan2(InputStream&, TagHandler&) (handler=..., is=...)
    at ../mpd-0.23.7/src/tag/ApeTag.cxx:82
#11 ScanGenericTags(InputStream&, TagHandler&) [clone .isra.0] (is=..., handler=...)
    at ../mpd-0.23.7/src/tag/Generic.cxx:35
#12 0x00005555555cc17b in tag_stream_scan(InputStream&, TagBuilder&, AudioFormat*)
    (audio_format=0x0, builder=..., is=...) at ../mpd-0.23.7/src/TagStream.cxx:93
#13 tag_archive_scan(ArchiveFile&, char const*, TagBuilder&)
    (builder=..., path_utf8=<optimized out>, archive=<optimized out>)
    at ../mpd-0.23.7/src/TagArchive.cxx:47
#14 Song::UpdateFileInArchive(ArchiveFile&) (this=0x7fffcc02a080, archive=<optimized out>)
    at ../mpd-0.23.7/src/SongUpdate.cxx:137
#15 0x00005555555d6377 in Song::LoadFromArchive(ArchiveFile&, char const*, Directory&)
    (parent=..., name_utf8=0x7fffe1368e67 "RECORDING.MOV", archive=...)
    at ../mpd-0.23.7/src/SongUpdate.cxx:115
#16 UpdateWalk::UpdateArchiveTree(ArchiveFile&, Directory&, char const*)
    (this=0x55555575f510, archive=..., directory=<optimized out>, name=<optimized out>)
    at ../mpd-0.23.7/src/db/update/Archive.cxx:77
#17 0x000055555566aa4f in UpdateArchiveVisitor::VisitArchiveEntry(char const*)
    (path_utf8=0x7fffe1368e51 "DATA/RECORDING/AUDIO/RECORDING.MOV", this=0x7fffe1369f10)
    at ../mpd-0.23.7/src/db/update/Archive.cxx:112
#18 Iso9660ArchiveFile::Visit(char*, unsigned long, unsigned long, ArchiveVisitor&) [clone .constprop.0]
    (this=0x7fffcc02a040, path=0x7fffe1368e50 "/DATA/RECORDING/AUDIO/RECORDING.MOV", length=23, visitor=..., capacity=<optimized out>) at ../mpd-0.23.7/src/archive/plugins/Iso9660ArchivePlugin.cxx:123
#19 0x000055555566ab02 in Iso9660ArchiveFile::Visit(char*, unsigned long, unsigned long, ArchiveVisitor&) [clone .constprop.0]
    (this=0x7fffcc02a040, path=0x7fffe1368e50 "/DATA/RECORDING/AUDIO/RECORDING.MOV", length=17, visitor=..., capacity=<optimized out>) at ../mpd-0.23.7/src/archive/plugins/Iso9660ArchivePlugin.cxx:120
#20 0x000055555566ab02 in Iso9660ArchiveFile::Visit(char*, unsigned long, unsigned long, ArchiveVisitor&) [clone .constprop.0]
    (this=0x7fffcc02a040, path=0x7fffe1368e50 "/DATA/RECORDING/AUDIO/RECORDING.MOV", length=6, visitor=..., capacity=<optimized out>) at ../mpd-0.23.7/src/archive/plugins/Iso9660ArchivePlugin.cxx:120
#21 0x000055555566ab02 in Iso9660ArchiveFile::Visit(char*, unsigned long, unsigned long, ArchiveVisitor&) [clone .constprop.0]
    (this=0x7fffcc02a040, path=0x7fffe1368e50 "/DATA/RECORDING/AUDIO/RECORDING.MOV", length=1, visitor=..., capacity=<optimized out>) at ../mpd-0.23.7/src/archive/plugins/Iso9660ArchivePlugin.cxx:120
#22 0x00005555556624ce in Iso9660ArchiveFile::Visit(ArchiveVisitor&)
    (this=<optimized out>, visitor=<optimized out>)
    at ../mpd-0.23.7/src/archive/plugins/Iso9660ArchivePlugin.cxx:144
#23 0x000055555563c7cd in UpdateWalk::UpdateArchiveFile(Directory&, std::basic_string_view<char, std::char_traits<char> >, StorageFileInfo const&, ArchivePlugin const&) (plugin=..., info=..., name="RECORDING.ISO", parent=..., this=0x55555575f510) at ../mpd-0.23.7/src/db/update/Archive.cxx:155
#24 UpdateWalk::UpdateArchiveFile(Directory&, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, StorageFileInfo const&) (info=..., suffix=Python Exception <class 'gdb.error'>: value has been optimized out
, name="RECORDING.ISO", directory=..., this=0x55555575f510) at ../mpd-0.23.7/src/db/update/Archive.cxx:167
#25 UpdateWalk::UpdateRegularFile(Directory&, char const*, StorageFileInfo const&) (info=..., name=0x7fffcc0213a0 "RECORDING.ISO", directory=..., this=0x55555575f510) at ../mpd-0.23.7/src/db/update/Walk.cxx:196
#26 UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) (this=0x55555575f510, directory=..., exclude_list=<optimized out>, name=0x7fffcc0213a0 "RECORDING.ISO", info=...) at ../mpd-0.23.7/src/db/update/Walk.cxx:208
#27 0x000055555563dce8 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) (this=0x55555575f510, directory=..., exclude_list=<optimized out>, info=...) at ../mpd-0.23.7/src/db/update/Walk.cxx:385
#28 0x000055555563bee2 in UpdateWalk::UpdateDirectoryChild(Directory&, ExcludeList const&, char const*, StorageFileInfo const&) (this=0x55555575f510, directory=..., exclude_list=..., name=0x7fffcc000be8 "A Capella", info=...) at ../mpd-0.23.7/src/db/update/Walk.cxx:222
#29 0x000055555563dce8 in UpdateWalk::UpdateDirectory(Directory&, ExcludeList const&, StorageFileInfo const&) (this=0x55555575f510, directory=..., exclude_list=<optimized out>, info=...) at ../mpd-0.23.7/src/db/update/Walk.cxx:385
#30 0x000055555563e8ae in UpdateWalk::Walk(Directory&, char const*, bool) (discard=<optimized out>, path=0x55555574f898 "", root=..., this=0x55555575f510) at ../mpd-0.23.7/src/db/update/Walk.cxx:529
#31 UpdateService::Task() (this=0x55555574f7f0) at ../mpd-0.23.7/src/db/update/Service.cxx:122
#32 BindMethodDetail::WrapperGenerator<void (UpdateService::*)() noexcept, &UpdateService::Task>::Invoke(void*) (_instance=0x55555574f7f0) at ../mpd-0.23.7/src/util/BindMethod.hxx:130
#33 0x00005555555d9c21 in BoundMethod<void () noexcept>::operator()() const (this=<optimized out>, this=<optimized out>) at ../mpd-0.23.7/src/util/BindMethod.hxx:78
#34 Thread::Run() (this=<optimized out>) at ../mpd-0.23.7/src/thread/Thread.cxx:63
#35 Thread::ThreadProc(void*) (ctx=<optimized out>) at ../mpd-0.23.7/src/thread/Thread.cxx:92
#36 0x00007ffff2c8c54d in  () at /usr/lib/libc.so.6
#37 0x00007ffff2d11874 in clone () at /usr/lib/libc.so.6

quit
```
This is on archlinux with all packages up to date at the time of writing

**Comment by MaxKellermann** [comment]
I need that specific ISO file.

**Comment by bishonenknife** [comment]
I've reproduced this (accidentally), I can provide the iso that caused this crash for me if necessary. Also on arch linux, most recent system upgrade was yesterday. I'm on mpd 0.23.9-1 and this is still happening.
[dump.txt](https://github.com/MusicPlayerDaemon/MPD/files/9474301/dump.txt)

**Comment by bishonenknife** [comment]
the file exceeded size limits on here so I've provided a drive link https://drive.google.com/file/d/1KTN37Aioqb0MkuaPztEoowUTf56aTtpM/view?usp=sharing
