### ISSUE TITLE
Compiling for Android attempts to link libmpd.so to a system library.

### ISSUE THREAD

**Issue by avuton** [MusicPlayerDaemon/MPD#1681]
When compiling for Android with 9866adff957f9beefd4a3f3fda26281984e0cb2f the compilation fails when trying to link to '/usr/bin/libz.so'. 

The command line used after referring to the user documentation:
PATH="$PATH:/home/avuton/Programs/android-sdk/build-tools/33.0.1/" ../../android/build.py ~/Programs/android-sdk/ ~/Programs/android-ndk/ arm64-v8a -Ddocumentation=off

I had to add documentation=off to avoid another failure and ] I had to edit the CURL build to avoid a build failure there, as well:
```
diff --git a/python/build/libs.py b/python/build/libs.py
index 4f35588e8..bf9405f41 100644
--- a/python/build/libs.py
+++ b/python/build/libs.py
@@ -399,6 +399,8 @@ curl = CmakeProject(
     [
         '-DBUILD_CURL_EXE=OFF',
         '-DBUILD_SHARED_LIBS=OFF',
+       '-DCURL_USE_LIBPSL=OFF',
+       '-DCURL_USE_LIBSSH2=OFF',
         '-DCURL_DISABLE_LDAP=ON',
         '-DCURL_DISABLE_TELNET=ON',
         '-DCURL_DISABLE_DICT=ON',
```

The linker fail:
```
[2/2] Linking target libmpd.so
FAILED: libmpd.so 
/home/avuton/Programs/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  -o libmpd.so libmpd.so.p/meson-generated_.._GitVersion.cxx.o libmpd.so.p/src_Main.cxx.o libmpd.so.p/src_protocol_ArgParser.cxx.o libmpd.so.p/src_command_CommandError.cxx.o libmpd.so.p/src_command_PositionArg.cxx.o libmpd.so.p/src_command_AllCommands.cxx.o libmpd.so.p/src_command_QueueCommands.cxx.o libmpd.so.p/src_command_TagCommands.cxx.o libmpd.so.p/src_command_PlayerCommands.cxx.o libmpd.so.p/src_command_PlaylistCommands.cxx.o libmpd.so.p/src_command_FileCommands.cxx.o libmpd.so.p/src_command_OutputCommands.cxx.o libmpd.so.p/src_command_MessageCommands.cxx.o libmpd.so.p/src_command_ClientCommands.cxx.o libmpd.so.p/src_command_PartitionCommands.cxx.o libmpd.so.p/src_command_OtherCommands.cxx.o libmpd.so.p/src_command_CommandListBuilder.cxx.o libmpd.so.p/src_Idle.cxx.o libmpd.so.p/src_IdleFlags.cxx.o libmpd.so.p/src_decoder_Thread.cxx.o libmpd.so.p/src_decoder_Control.cxx.o libmpd.so.p/src_decoder_Bridge.cxx.o libmpd.so.p/src_decoder_DecoderPrint.cxx.o libmpd.so.p/src_client_Listener.cxx.o libmpd.so.p/src_client_Client.cxx.o libmpd.so.p/src_client_Config.cxx.o libmpd.so.p/src_client_Domain.cxx.o libmpd.so.p/src_client_Event.cxx.o libmpd.so.p/src_client_Expire.cxx.o libmpd.so.p/src_client_Idle.cxx.o libmpd.so.p/src_client_List.cxx.o libmpd.so.p/src_client_New.cxx.o libmpd.so.p/src_client_Process.cxx.o libmpd.so.p/src_client_Read.cxx.o libmpd.so.p/src_client_Write.cxx.o libmpd.so.p/src_client_Message.cxx.o libmpd.so.p/src_client_Subscribe.cxx.o libmpd.so.p/src_client_File.cxx.o libmpd.so.p/src_client_Response.cxx.o libmpd.so.p/src_client_ThreadBackgroundCommand.cxx.o libmpd.so.p/src_Listen.cxx.o libmpd.so.p/src_LogInit.cxx.o libmpd.so.p/src_ls.cxx.o libmpd.so.p/src_Instance.cxx.o libmpd.so.p/src_MusicBuffer.cxx.o libmpd.so.p/src_MusicPipe.cxx.o libmpd.so.p/src_MusicChunk.cxx.o libmpd.so.p/src_MusicChunkPtr.cxx.o libmpd.so.p/src_Mapper.cxx.o libmpd.so.p/src_Partition.cxx.o libmpd.so.p/src_Permission.cxx.o libmpd.so.p/src_player_CrossFade.cxx.o libmpd.so.p/src_player_Thread.cxx.o libmpd.so.p/src_player_Control.cxx.o libmpd.so.p/src_PlaylistError.cxx.o libmpd.so.p/src_PlaylistPrint.cxx.o libmpd.so.p/src_PlaylistSave.cxx.o libmpd.so.p/src_playlist_PlaylistStream.cxx.o libmpd.so.p/src_playlist_PlaylistMapper.cxx.o libmpd.so.p/src_playlist_PlaylistAny.cxx.o libmpd.so.p/src_playlist_PlaylistSong.cxx.o libmpd.so.p/src_playlist_PlaylistQueue.cxx.o libmpd.so.p/src_playlist_Print.cxx.o libmpd.so.p/src_db_PlaylistVector.cxx.o libmpd.so.p/src_queue_Queue.cxx.o libmpd.so.p/src_queue_QueuePrint.cxx.o libmpd.so.p/src_queue_QueueSave.cxx.o libmpd.so.p/src_queue_Playlist.cxx.o libmpd.so.p/src_queue_PlaylistControl.cxx.o libmpd.so.p/src_queue_PlaylistEdit.cxx.o libmpd.so.p/src_queue_PlaylistTag.cxx.o libmpd.so.p/src_queue_PlaylistState.cxx.o libmpd.so.p/src_ReplayGainGlobal.cxx.o libmpd.so.p/src_LocateUri.cxx.o libmpd.so.p/src_SongUpdate.cxx.o libmpd.so.p/src_SongLoader.cxx.o libmpd.so.p/src_SongPrint.cxx.o libmpd.so.p/src_SongSave.cxx.o libmpd.so.p/src_StateFile.cxx.o libmpd.so.p/src_StateFileConfig.cxx.o libmpd.so.p/src_Stats.cxx.o libmpd.so.p/src_TagPrint.cxx.o libmpd.so.p/src_TagSave.cxx.o libmpd.so.p/src_TagFile.cxx.o libmpd.so.p/src_TagStream.cxx.o libmpd.so.p/src_TagAny.cxx.o libmpd.so.p/src_TimePrint.cxx.o libmpd.so.p/src_mixer_Memento.cxx.o libmpd.so.p/src_PlaylistFile.cxx.o libmpd.so.p/src_android_Context.cxx.o libmpd.so.p/src_android_AudioManager.cxx.o libmpd.so.p/src_android_Environment.cxx.o libmpd.so.p/src_android_LogListener.cxx.o libmpd.so.p/src_storage_StorageState.cxx.o libmpd.so.p/src_queue_PlaylistUpdate.cxx.o libmpd.so.p/src_command_StorageCommands.cxx.o libmpd.so.p/src_command_DatabaseCommands.cxx.o libmpd.so.p/src_RemoteTagCache.cxx.o libmpd.so.p/src_command_StickerCommands.cxx.o libmpd.so.p/src_sticker_Database.cxx.o libmpd.so.p/src_sticker_Print.cxx.o libmpd.so.p/src_sticker_SongSticker.cxx.o -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libmpd.so -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Os -g -fpic -target aarch64-linux-android21 -fvisibility=hidden -fdata-sections -ffunction-sections -static-libstdc++ -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib libbasic.a src/config/libfs.a liblog.a subprojects/fmt-9.1.0/libfmt.a src/fs/libfs.a src/lib/zlib/libzlib.a src/io/libio.a src/system/libsystem.a src/lib/icu/libicu.a src/util/libutil.a src/net/libnet.a src/event/libevent.a src/thread/libthread.a src/input/libinput_glue.a src/input/plugins/libinput_plugins.a src/lib/curl/libcurl.a src/lib/ffmpeg/libffmpeg.a src/lib/nfs/libnfs.a src/lib/crypto/libcrypto_md5.a src/input/libinput_api.a src/pcm/libpcm.a src/pcm/libpcm_basic.a src/tag/libtag.a src/time/libtime.a src/output/liboutput_glue.a src/filter/libfilter_glue.a src/filter/plugins/libfilter_plugins.a src/filter/libfilter_api.a src/mixer/plugins/libmixer_plugins.a src/output/plugins/liboutput_plugins.a src/output/liboutput_api.a src/mixer/libmixer_glue.a src/decoder/libdecoder_glue.a src/decoder/plugins/libdecoder_plugins.a src/lib/xiph/libflac.a src/lib/xiph/libxiph.a subprojects/libvorbis-1.3.7/lib/libvorbis.a src/lib/xiph/libvorbis.a src/lib/xiph/libogg.a src/lib/crypto/libcrypto_base64.a src/decoder/libdecoder_api.a src/encoder/libencoder_glue.a src/encoder/plugins/libencoder_plugins.a subprojects/libvorbis-1.3.7/lib/libvorbisenc.a src/playlist/libplaylist_glue.a src/playlist/plugins/libplaylist_plugins.a src/lib/expat/libexpat.a subprojects/expat-2.5.0/libexpat.a src/playlist/libplaylist_api.a src/db/libdb_glue.a src/db/plugins/libdb_plugins.a src/db/libdb_api.a src/storage/libstorage_api.a src/storage/libstorage_glue.a src/storage/plugins/libstorage_plugins.a src/song/libsong.a src/lib/sqlite/libsqlite.a subprojects/sqlite-amalgamation-3390300/libsqlite3.a src/java/libjava.a -Wl,--no-undefined,-shared,-Bsymbolic -llog -lz -lz -lz -pthread /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libcurl.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libssl.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libcrypto.a /usr/lib/libz.so /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libavformat.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libavcodec.a /home/avuton/Programs/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/21/libz.so /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libavutil.a -lm /home/avuton/Programs/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/14.0.6/lib/linux/aarch64/libatomic.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libnfs.a -lOpenSLES /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libFLAC.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libmodplug.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libopus.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libogg.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libWildMidi.a /home/avuton/src/MPD/output/android/lib/aarch64-linux-android/root/lib/libmpdclient.a -Wl,--end-group
ld: error: /usr/lib/libz.so is incompatible with aarch64linux
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/avuton/src/MPD/output/android/../../android/build.py", line 186, in <module>
    subprocess.check_call(['/usr/bin/ninja'], env=toolchain.env)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/ninja']' returned non-zero exit status 1.
```

**Comment by MaxKellermann** [comment]
Duplicate of https://github.com/MusicPlayerDaemon/MPD/issues/1375 ?

**Comment by avuton** [comment]
At my last glance, I thought it was unrelated. Now I think it is, so I'll close this as duplicate.
