### ISSUE TITLE
crash of mpd-git at the end of current playlist

### ISSUE THREAD

**Issue by mistepien** [MusicPlayerDaemon/MPD#208]
musl+alsa 1.1.5 + mpd-git (v0.20.15-855-g1da64fb79-dirty)
conditions the same like in https://github.com/MusicPlayerDaemon/MPD/issues/203

when the last track ended the mpd is dead.

output of gdb:

> client: [3] command returned 0
client: [3] process command "playlistinfo "792""
client: [3] command returned 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  soxr error: null pointer

>Thread 5 "output:DAC,0 [U" received signal SIGABRT, Aborted.
[Switching to LWP 13906]
0xb7f6bab9 in __kernel_vsyscall ()
(gdb) bt
#0  0xb7f6bab9 in __kernel_vsyscall ()
#1  0xb7f8a0b8 in __vsyscall () at src/internal/i386/syscall.s:19
#2  0xb7fb5408 in __syscall4 (a4=8, a3=0, a2=-1235589712, a1=2, n=175)
    at ./arch/i386/syscall_arch.h:37
#3  __restore_sigs (set=0xb65a65b0) at src/signal/block.c:43
#4  0xb7fb55d6 in raise (sig=6) at src/signal/raise.c:13
#5  0xb7f880a6 in abort () at src/exit/abort.c:9
#6  0xb6c3a16b in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/libstdc++.so.6
#7  0xb6c3831c in ?? () from /usr/lib/libstdc++.so.6
#8  0xb6c3750b in ?? () from /usr/lib/libstdc++.so.6
#9  0xb6c37ded in __gxx_personality_v0 () from /usr/lib/libstdc++.so.6
#10 0xb6bbcd5b in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x9b33860, 
    context=context@entry=0xb65a6910) at ../../../libgcc/unwind.inc:62
#11 0xb6bbcff4 in _Unwind_RaiseException (exc=0x9b33860)
    at ../../../libgcc/unwind.inc:131
#12 0xb6c3861a in __cxa_throw () from /usr/lib/libstdc++.so.6
#13 0x080a9f96 in SoxrPcmResampler::Flush() ()
#14 0x080a958e in GluePcmResampler::Flush() ()
#15 0x080a82d5 in PcmConvert::Flush() ()
#16 0x080a63ab in ConvertFilter::Flush() ()
#17 0x080a7327 in FilterObserver::Proxy::Flush() ()
#18 0x080a5cff in ChainFilter::Flush() ()
#19 0x08073565 in AudioOutputSource::Flush() ()
#20 0x08074031 in AudioOutputControl::InternalDrain() ()
#21 0x08074446 in AudioOutputControl::Task() ()
#22 0x080b129e in Thread::ThreadProc(void*) ()
#23 0xb7fc3ee4 in start (p=0xb65a6d50) at src/thread/pthread_create.c:150
#24 0xb7fc25bd in __clone () at src/thread/i386/clone.s:36
#25 0x00000000 in ?? ()

**Comment by mistepien** [comment]
now it works just fine. thanks.
