### ISSUE TITLE
udisks2 plugin does not show any files

### ISSUE THREAD

**Issue by carnager** [MusicPlayerDaemon/MPD#288]
Trying out the new udisks2 plugin, I wasnt able to add any music from a USB stick yet.

Info about my build:

```
Music Player Daemon 0.21 (v0.20.20-976-gcccf35d14)

Copyright (C) 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2017 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// http:// https:// mms:// mmsh:// mmst:// mmsu:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// cdda:// alsa:// qobuz:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

Here is what has been done with the help of python-mpd2:

```
>>> m.connect('tauron', '6600')
>>> m.listneighbors()
[{'neighbor': 'udisks://by-uuid-425e69a9-0f06-4c3f-b54c-62667af2e918', 'name': '/org/freedesktop/UDisks2/block_devices/sde1'}, {'neighbor': 'udisks://by-id-ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E0322940-part9', 'name': '/org/freedesktop/UDisks2/block_devices/sdc9'}, {'neighbor': 'udisks://by-id-ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E0322940-part1', 'name': '/org/freedesktop/UDisks2/block_devices/sdc1'}, {'neighbor': 'udisks://by-id-ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E0302208-part9', 'name': '/org/freedesktop/UDisks2/block_devices/sdb9'}, {'neighbor': 'udisks://by-id-ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E0302208-part1', 'name': '/org/freedesktop/UDisks2/block_devices/sdb1'}, {'neighbor': 'udisks://by-id-ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E0295631-part9', 'name': '/org/freedesktop/UDisks2/block_devices/sdd9'}, {'neighbor': 'udisks://by-id-ata-WDC_WD40EFRX-68WT0N0_WD-WCC4E0295631-part1', 'name': '/org/freedesktop/UDisks2/block_devices/sdd1'}, {'neighbor': 'udisks://by-id-ata-VB0250EAVER_Z2AE6XJJ-part4', 'name': '/org/freedesktop/UDisks2/block_devices/sda4'}]
>>> m.mount ('foobar', 'udisks://by-uuid-425e69a9-0f06-4c3f-b54c-62667af2e918')
>>> m.listinfo('foobar')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'MPDClient' object has no attribute 'listinfo'
>>> m.lsinfo('foobar')
[]
>>> m.lsinfo('foobar/')
[]
```

And here is mpds verbose log:

```
carnager@tauron ~/.mpd > mpd --verbose --stdout --no-daemon
config_file: loading file /home/carnager/.mpd/mpd.conf
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.2.1
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
wildmidi: configuration file does not exist: /etc/timidity/timidity.cfg
simple_db: reading DB
exception: Input plugin 'tidal' is unavailable: No Tidal application token configured
exception: Input plugin 'qobuz' is unavailable: No Qobuz app_id configured
curl: version 7.59.0
curl: with OpenSSL/1.1.0h
avahi: Initializing interface
avahi: Client changed to state 2
avahi: Client is RUNNING
avahi: Registering service _mpd._tcp/Music Player
avahi: Service group changed to state 0
avahi: Service group is UNCOMMITED
state_file: Loading state file /home/carnager/.mpd/state
exception: Failed to open /home/carnager/.mpd/state: No such file or directory
config: option 'music_directory' on line 19 was not recognized
avahi: Service group changed to state 1
avahi: Service group is REGISTERING
client: [0] opened from 192.168.0.13:44358
client: [0] process command list
client: process command "status"
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [0] process command list returned 0
client: [0] closed
avahi: Service group changed to state 2
avahi: Service 'Music Player' successfully established.
client: [1] opened from 192.168.0.13:44364
client: [1] process command list
client: process command "status"
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [1] process command list returned 0
client: [1] closed
client: [2] opened from 192.168.0.13:44366
client: [3] opened from 192.168.0.13:44368
client: [3] process command list
client: process command "status"
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [3] process command list returned 0
client: [3] closed
client: [2] process command "listneighbors"
client: [2] command returned 0
client: [2] process command "mount "foobar" "udisks://by-uuid-425e69a9-0f06-4c3f-b54c-62667af2e918""
simple_db: reading DB
client: [2] command returned 0
client: [4] opened from 192.168.0.13:44370
client: [4] process command list
client: process command "status"
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [4] process command list returned 0
client: [4] closed
client: [5] opened from 192.168.0.13:44372
client: [5] process command list
client: process command "status"
client: command returned 0
client: [2] process command "lsinfo "foobar""
client: [2] command returned 0
```

**Comment by MaxKellermann** [comment]
Try updating the path first. i.e. `mpc update foobar`

**Comment by carnager** [comment]
It always says "Already updating", no matter how long I wait.

But there is only 20 files on that USB stick.

**Comment by MaxKellermann** [comment]
Backtrace of all threads when MPD tells you it's already updating.

**Comment by MaxKellermann** [comment]
Is the filesystem mounted in the kernel? Check /proc/mounts or /proc/self/mountinfo

**Comment by carnager** [comment]
No, the stick never gets mounted, it seems.

**Comment by MaxKellermann** [comment]
It will be mounted at the first access, but if MPD never starts updating, there will not be an access. Backtrace!

**Comment by carnager** [comment]
Ok, this is the backtrace when the thread started and the next from when the thread exited:

```
[Switching to Thread 0x7ffff7f7a8c0 (LWP 2862)]

Thread 1 "mpd" hit Breakpoint 1, 0x00007ffff038f3b4 in pthread_create@@GLIBC_2.2.5 () from /usr/lib/libpthread.so.0
(gdb) thread apply all bt

Thread 8 (Thread 0x7fffc3fff700 (LWP 2873)):
#0  0x00007fffed7b7cd9 in poll () from /usr/lib/libc.so.6
#1  0x00007fffefa76773 in ?? () from /usr/lib/libpulse.so.0
#2  0x00007fffefa67bd0 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#3  0x00007fffefa68271 in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#4  0x00007fffefa68301 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#5  0x00007fffefa766ae in ?? () from /usr/lib/libpulse.so.0
#6  0x00007fffe25c081c in ?? () from /usr/lib/pulseaudio/libpulsecommon-11.1.so
#7  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7fffd0f57700 (LWP 2872)):
#0  0x00007ffff039507c in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005555555b36d3 in AudioOutputControl::Task() ()
#2  0x0000555555635fed in Thread::ThreadProc(void*) ()
#3  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffd1758700 (LWP 2871)):
#0  0x00007ffff039507c in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005555555b36d3 in AudioOutputControl::Task() ()
#2  0x0000555555635fed in Thread::ThreadProc(void*) ()
#3  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffd2359700 (LWP 2869)):
#0  0x00007ffff039507c in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005555555b5f9e in DecoderControl::RunThread() ()
#2  0x0000555555635fed in Thread::ThreadProc(void*) ()
#3  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6
---Type <return> to continue, or q <return> to quit---

Thread 4 (Thread 0x7fffd2b5a700 (LWP 2868)):
#0  0x00007ffff039507c in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000055555558e2fe in PlayerControl::RunThread() ()
#2  0x0000555555635fed in Thread::ThreadProc(void*) ()
#3  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffd335b700 (LWP 2867)):
#0  0x00007fffed7c2627 in epoll_wait () from /usr/lib/libc.so.6
#1  0x0000555555635d28 in EventLoop::Run() ()
#2  0x0000555555634876 in EventThread::Run() ()
#3  0x0000555555635fed in Thread::ThreadProc(void*) ()
#4  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffd3b5c700 (LWP 2866)):
#0  0x00007fffed7c2627 in epoll_wait () from /usr/lib/libc.so.6
#1  0x0000555555635d28 in EventLoop::Run() ()
#2  0x0000555555634876 in EventThread::Run() ()
#3  0x0000555555635fed in Thread::ThreadProc(void*) ()
#4  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7f7a8c0 (LWP 2862)):
#0  0x00007ffff038f3b4 in pthread_create@@GLIBC_2.2.5 () from /usr/lib/libpthread.so.0
#1  0x000055555563601c in Thread::Start() ()
#2  0x000055555559f62e in UpdateService::StartThread(UpdateQueueItem&&) ()
#3  0x000055555559f88b in UpdateService::Enqueue(char const*, bool) ()
#4  0x0000555555586bdd in handle_update(Client&, Request, Response&, bool) ()
#5  0x0000555555582e90 in command_process(Client&, unsigned int, char*) ()
#6  0x00005555555b7d9c in client_process_line(Client&, char*) ()
---Type <return> to continue, or q <return> to quit---
#7  0x00005555555880dd in Client::OnSocketInput(void*, unsigned long) ()
#8  0x0000555555632a9e in BufferedSocket::ResumeInput() ()
#9  0x0000555555632be1 in BufferedSocket::OnSocketReady(unsigned int) ()
#10 0x00005555556325b9 in SocketMonitor::Dispatch(unsigned int) ()
#11 0x0000555555635da2 in EventLoop::Run() ()
#12 0x000055555557f416 in mpd_main(int, char**) ()
#13 0x00007fffed6ec9a7 in __libc_start_main () from /usr/lib/libc.so.6
#14 0x000055555557ea4a in _start ()
(gdb) continue
Continuing.
[New Thread 0x7fffc37fe700 (LWP 2876)]
[Thread 0x7fffc37fe700 (LWP 2876) exited]

Thread 1 "mpd" hit Breakpoint 1, 0x00007ffff038f3b4 in pthread_create@@GLIBC_2.2.5 () from /usr/lib/libpthread.so.0
(gdb) thread apply all bt

Thread 8 (Thread 0x7fffc3fff700 (LWP 2873)):
#0  0x00007fffed7b7cd9 in poll () from /usr/lib/libc.so.6
#1  0x00007fffefa76773 in ?? () from /usr/lib/libpulse.so.0
#2  0x00007fffefa67bd0 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#3  0x00007fffefa68271 in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#4  0x00007fffefa68301 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#5  0x00007fffefa766ae in ?? () from /usr/lib/libpulse.so.0
#6  0x00007fffe25c081c in ?? () from /usr/lib/pulseaudio/libpulsecommon-11.1.so
#7  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7fffd0f57700 (LWP 2872)):
#0  0x00007ffff039507c in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005555555b36d3 in AudioOutputControl::Task() ()
#2  0x0000555555635fed in Thread::ThreadProc(void*) ()
#3  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7fffd1758700 (LWP 2871)):
#0  0x00007ffff039507c in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005555555b36d3 in AudioOutputControl::Task() ()
#2  0x0000555555635fed in Thread::ThreadProc(void*) ()
#3  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7fffd2359700 (LWP 2869)):
#0  0x00007ffff039507c in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x00005555555b5f9e in DecoderControl::RunThread() ()
#2  0x0000555555635fed in Thread::ThreadProc(void*) ()
#3  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6
---Type <return> to continue, or q <return> to quit---

Thread 4 (Thread 0x7fffd2b5a700 (LWP 2868)):
#0  0x00007ffff039507c in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x000055555558e2fe in PlayerControl::RunThread() ()
#2  0x0000555555635fed in Thread::ThreadProc(void*) ()
#3  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#4  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fffd335b700 (LWP 2867)):
#0  0x00007fffed7c2627 in epoll_wait () from /usr/lib/libc.so.6
#1  0x0000555555635d28 in EventLoop::Run() ()
#2  0x0000555555634876 in EventThread::Run() ()
#3  0x0000555555635fed in Thread::ThreadProc(void*) ()
#4  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7fffd3b5c700 (LWP 2866)):
#0  0x00007fffed7c2627 in epoll_wait () from /usr/lib/libc.so.6
#1  0x0000555555635d28 in EventLoop::Run() ()
#2  0x0000555555634876 in EventThread::Run() ()
#3  0x0000555555635fed in Thread::ThreadProc(void*) ()
#4  0x00007ffff038f0bc in start_thread () from /usr/lib/libpthread.so.0
#5  0x00007fffed7c22ff in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ffff7f7a8c0 (LWP 2862)):
#0  0x00007ffff038f3b4 in pthread_create@@GLIBC_2.2.5 () from /usr/lib/libpthread.so.0
#1  0x000055555563601c in Thread::Start() ()
#2  0x000055555559f62e in UpdateService::StartThread(UpdateQueueItem&&) ()
#3  0x000055555559f9cb in UpdateService::RunDeferred() ()
#4  0x000055555563562d in EventLoop::HandleDeferred() ()
#5  0x0000555555635688 in EventLoop::OnSocketReady(unsigned int) ()
#6  0x00005555556325b9 in SocketMonitor::Dispatch(unsigned int) ()
---Type <return> to continue, or q <return> to quit---
#7  0x0000555555635da2 in EventLoop::Run() ()
#8  0x000055555557f416 in mpd_main(int, char**) ()
#9  0x00007fffed6ec9a7 in __libc_start_main () from /usr/lib/libc.so.6
#10 0x000055555557ea4a in _start ()
(gdb) continue
Continuing.
[New Thread 0x7fffc37fe700 (LWP 2878)]
[Thread 0x7fffc37fe700 (LWP 2878) exited]
```

**Comment by MaxKellermann** [comment]
Neither backtrace shows the situation when MPD told you "update already running", does it?

**Comment by carnager** [comment]
Somehow I cannot make it stop there. 

```
[New Thread 0x7fffc37fe700 (LWP 2874)]
[Thread 0x7fffc37fe700 (LWP 2874) exited]
```
this is the update thread. Any hint how I can make gdb stop there?

**Comment by MaxKellermann** [comment]
If MPD tells you "Already updating", it will not create a new thread. So if you see this gdb output, then you're probably not seeing "Already updating". Something must be wrong with your problem description. Since we're not anymore talking about your initial problem (which is already solved), I think you should start a new bug report from scratch and explain what you see and post the backtrace matching this situation.

**Comment by carnager** [comment]
The initial problem was "udisks plugin does not show any files". It's even the title of this issue. I don't see where this got solved.
