### ISSUE TITLE
FLAC comment handling code is fragile

### ISSUE THREAD

**Issue by czimman** [MusicPlayerDaemon/MPD#335]
In src/lib/xiph/FlacStreamMetadata.cxx:100  

static void
flac_scan_comment(const FLAC__StreamMetadata_VorbisComment_Entry *entry,
		  TagHandler &handler) noexcept
{
	if (handler.WantPair()) {
		const char *comment = (const char *)entry->entry;
		const DivideString split(comment, '=');
		if (split.IsDefined() && !split.empty())
			handler.OnPair(split.GetFirst(), split.GetSecond());
	}

If comment is NULL, split() will segfault

**Comment by czimman** [comment]
Is this a fix?

if (handler.WantPair()) {
const char *comment = (const char *)entry->entry;
if(!comment) return;
[...]


I'm familiar enough with the code base to know for sure, but it stops the segfault from occurring.

**Comment by czimman** [comment]
For the purposes of completeness, here's the obligatory stack trace (bug "fix" removed):

#0  __strchr_sse2 () at ../sysdeps/x86_64/multiarch/../strchr.S:32
#1  0x00005555556d6ba9 in DivideString::DivideString (this=0x7fffca3fb0b0, s=0x0, separator=61 '=', strip=false) at src/util/DivideString.cxx:28
#2  0x000055555564e14a in flac_scan_comment (entry=0x7fffc00183f0, handler=...) at src/lib/xiph/FlacStreamMetadata.cxx:102
#3  0x000055555564e29c in flac_scan_comments (comment=0x7fffc0018c40, handler=...) at src/lib/xiph/FlacStreamMetadata.cxx:124
#4  0x000055555564e3a9 in flac_scan_metadata (block=0x7fffc0018c30, handler=...) at src/lib/xiph/FlacStreamMetadata.cxx:159
#5  0x000055555564dedc in FlacMetadataChain::Scan (this=0x7fffca3fb190, handler=...) at src/lib/xiph/FlacMetadataChain.cxx:48
#6  0x0000555555645ddc in flac_scan_file (path_fs=..., handler=...) at src/decoder/plugins/FlacDecoderPlugin.cxx:83
#7  0x00005555555b3a7b in DecoderPlugin::ScanFile<Path> (this=0x5555559a72a0 <flac_decoder_plugin>, path_fs=..., handler=...) at src/decoder/DecoderPlugin.hxx:140
#8  0x00005555555b3715 in TagFileScan::ScanFile (this=0x7fffca3fb290, plugin=...) at src/TagFile.cxx:52
#9  0x00005555555b384c in TagFileScan::Scan (this=0x7fffca3fb290, plugin=...) at src/TagFile.cxx:79
#10 0x00005555555b38bc in <lambda(const DecoderPlugin&)>::operator()(const DecoderPlugin &) const (__closure=0x7fffca3fb258, plugin=...) at src/TagFile.cxx:99
#11 0x00005555555b3b65 in decoder_plugins_try<ScanFileTagsNoGeneric(Path, TagHandler&)::<lambda(const DecoderPlugin&)> >(<lambda(const DecoderPlugin&)>) (f=...)
    at src/decoder/DecoderList.hxx:61
#12 0x00005555555b3960 in ScanFileTagsNoGeneric (path_fs=..., handler=...) at src/TagFile.cxx:99
#13 0x00005555555b39c7 in ScanFileTagsWithGeneric (path=..., builder=..., audio_format=0x7fffca3fb408) at src/TagFile.cxx:108
#14 0x00005555555b1765 in Song::UpdateFile (this=0x555555a42ea0, storage=...) at src/SongUpdate.cxx:90
#15 0x00005555555c8f9d in UpdateWalk::UpdateSongFile2 (this=0x555555afa6c0, directory=..., 
    name=0x7fffc0018090 "your song name here.flac", suffix=0x7fffc00180bc "flac", info=...) at src/db/update/UpdateSong.cxx:84
#16 0x00005555555c9053 in UpdateWalk::UpdateSongFile (this=0x555555afa6c0, directory=..., name=0x7fffc0018090 "your song name here.flac", 
    suffix=0x7fffc00180bc "flac", info=...) at src/db/update/UpdateSong.cxx:103
#17 0x00005555555c6637 in UpdateWalk::UpdateRegularFile (this=0x555555afa6c0, directory=..., 
    name=0x7fffc0018090 "your song name here.flac", info=...) at src/db/update/Walk.cxx:204
#18 0x00005555555c66d7 in UpdateWalk::UpdateDirectoryChild (this=0x555555afa6c0, directory=..., exclude_list=..., 
    name=0x7fffc0018090 "your song name here.flac", info=...) at src/db/update/Walk.cxx:217
#19 0x00005555555c6f1c in UpdateWalk::UpdateDirectory (this=0x555555afa6c0, directory=..., exclude_list=..., info=...) at src/db/update/Walk.cxx:381
#20 0x00005555555c676c in UpdateWalk::UpdateDirectoryChild (this=0x555555afa6c0, directory=..., exclude_list=..., name=0x7fffc0008c18 "Discography", info=...)
    at src/db/update/Walk.cxx:231
#21 0x00005555555c6f1c in UpdateWalk::UpdateDirectory (this=0x555555afa6c0, directory=..., exclude_list=..., info=...) at src/db/update/Walk.cxx:381
#22 0x00005555555c676c in UpdateWalk::UpdateDirectoryChild (this=0x555555afa6c0, directory=..., exclude_list=..., name=0x7fffc001ed00 "artist", info=...)
    at src/db/update/Walk.cxx:231
#23 0x00005555555c6f1c in UpdateWalk::UpdateDirectory (this=0x555555afa6c0, directory=..., exclude_list=..., info=...) at src/db/update/Walk.cxx:381
#24 0x00005555555c74a4 in UpdateWalk::Walk (this=0x555555afa6c0, root=..., path=0x555555a0f7d8 "", discard=true) at src/db/update/Walk.cxx:499
#25 0x00005555555c43c8 in UpdateService::Task (this=0x555555a0f730) at src/db/update/Service.cxx:127
#26 0x00005555555c4ca7 in BindMethodDetail::BindMethodWrapperGenerator2<UpdateService, void (UpdateService::*)(), &UpdateService::Task, void>::Invoke (
    _instance=0x555555a0f730) at ./src/util/BindMethod.hxx:147
#27 0x00005555556c3258 in BoundMethod<void ()>::operator()() const (this=0x555555a0f780) at ./src/util/BindMethod.hxx:77
#28 0x00005555556cb0ec in Thread::Run (this=0x555555a0f780) at src/thread/Thread.cxx:64
#29 0x00005555556cb110 in Thread::ThreadProc (ctx=0x555555a0f780) at src/thread/Thread.cxx:93
#30 0x00007fffee944494 in start_thread (arg=0x7fffca3fc700) at pthread_create.c:333
#31 0x00007fffea1e8acf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

For the avoidance of doubt, the code was built -g (e.g. sans -O2).

Maybe a better "fix" is:

static void
flac_scan_comment(const FLAC__StreamMetadata_VorbisComment_Entry *entry,
		  TagHandler &handler) noexcept
{
	if(!entry || !entry->entry)
		return;
[...]
}
