### ISSUE TITLE
mpd crash HTTP stream output

### ISSUE THREAD

**Issue by TomDBR** [MusicPlayerDaemon/MPD#411]
MPD crashes every time i try playing music i just added to an empty playlist.
Note that something has to be in the playlist before clearing it, otherwise it won't crash.

exact steps:
1. mpc clear
2. mpc add someartist
3. mpc play

backtrace included
[https://gist.github.com/TomDBR/661d18d975b0cde70ba7b361183fbee8](https://gist.github.com/TomDBR/661d18d975b0cde70ba7b361183fbee8)

The crash doesn't happen when i turn off the HTTP stream output

**Comment by MaxKellermann** [comment]
https://www.musicpd.org/help/

**Comment by MaxKellermann** [comment]
btw your backtrace is useless because there are no line numbers.

**Comment by TomDBR** [comment]
[https://gist.github.com/TomDBR/4e1d1be893afff778c599381e7b41a7b](https://gist.github.com/TomDBR/4e1d1be893afff778c599381e7b41a7b)

**Comment by TomDBR** [comment]
Unlike last time i actually built from source now, instead of trying to edit the package that came with my distro.
I still get crashes by following the aforementioned steps, except it only happens with certain songs now, where before I could add any artist and it'd cause the crash.

like before, turning off the http stream output still stops it from crashing.
```
client: [2] closed
mpd: ../../src/output/SharedPipeConsumer.cxx:50: bool SharedPipeConsumer::IsConsumed(const MusicChunk&) const: Assertion `&_chunk == chunk || pipe->Contains(chunk)' failed.
client: [1] process command "status"

Thread 4 "player" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe277f700 (LWP 1463)]
0x00007ffff019bd7f in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff019bd7f in raise () from /usr/lib/libc.so.6
#1  0x00007ffff0186672 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff0186548 in __assert_fail_base.cold.0 () from /usr/lib/libc.so.6
#3  0x00007ffff0194396 in __assert_fail () from /usr/lib/libc.so.6
#4  0x0000555555600be2 in SharedPipeConsumer::IsConsumed (this=this@entry=0x555555745e40, _chunk=...) at /usr/include/c++/8.2.1/bits/unique_ptr.h:695
#5  0x00005555555ff20b in AudioOutputSource::IsChunkConsumed (chunk=..., this=0x555555745e30) at ../../src/output/Source.hxx:191
#6  AudioOutputControl::IsChunkConsumed (chunk=..., this=0x555555745e20) at ../../src/output/Control.cxx:277
#7  AudioOutputControl::LockIsChunkConsumed (this=0x555555745e20, chunk=...) at ../../src/output/Control.cxx:284
#8  0x00005555555fd164 in MultipleOutputs::IsChunkConsumed (chunk=0x7fffe137e000, this=0x55555572bd10) at ../../src/output/MultipleOutputs.cxx:280
#9  MultipleOutputs::CheckPipe (this=0x55555572bd10) at ../../src/output/MultipleOutputs.cxx:322
#10 0x00005555555a6ae5 in PlayerControl::WaitOutputConsumed (this=this@entry=0x55555572bd50, threshold=threshold@entry=64)
    at ../../src/player/Control.cxx:51
#11 0x00005555555a4c8e in PlayerControl::LockWaitOutputConsumed (threshold=64, this=0x55555572bd50) at ../../src/player/Control.hxx:433
#12 Player::PlayNextChunk (this=this@entry=0x7fffe277e910) at ../../src/player/Thread.cxx:809
#13 0x00005555555a62cd in Player::Run (this=this@entry=0x7fffe277e910) at ../../src/player/Thread.cxx:1043
#14 0x00005555555a4a14 in do_play (buffer=..., dc=..., pc=...) at ../../src/player/Thread.cxx:1113
#15 PlayerControl::RunThread (this=0x55555572bd50) at ../../src/player/Thread.cxx:1138
#16 0x00005555555ce7a3 in BoundMethod<void ()>::operator()() const (this=0x55555572bd78, this=0x55555572bd78) at ../../src/util/BindMethod.hxx:76
#17 Thread::Run (this=0x55555572bd78) at ../../src/thread/Thread.cxx:64
#18 Thread::ThreadProc (ctx=0x55555572bd78) at ../../src/thread/Thread.cxx:93
#19 0x00007ffff3d14a9d in start_thread () from /usr/lib/libpthread.so.0
#20 0x00007ffff025fb23 in clone () from /usr/lib/libc.so.6
(gdb) 
```

**Comment by MaxKellermann** [comment]
This is a different bug which I also found when I debugged your initial bug report - please make this a new bug report, and I'll fix it soon.
