### ISSUE TITLE
Segmentation fault when playing HTTP streams on dirty mpdstate

### ISSUE THREAD

**Issue by lae** [MusicPlayerDaemon/MPD#412]
Possibly related to #411, but I still hit a segfault without `always_on` on latest master (b1fe10590).

On a clean `mpdstate` (which I guess is also deleted when upgrading from 0.20?), mpd functions fine and I can listen to HTTP streams. However, after restarting mpd once, attempting to open an HTTP stream causes mpd to segfault.

simplified mpd.conf (segfault also happens with a flac encoded stream):
```
pid_file "/run/mpd/mpd.pid"
db_file "/var/lib/mpd/mpd.db"
state_file "/var/lib/mpd/mpdstate"
playlist_directory "/var/lib/mpd/playlists"
log_file "/var/lib/mpd/mpd.log"

music_directory "/home/lae/data"

audio_output {
    type        "httpd"
    name        "kirie radio (mp3)"
    encoder     "lame"
    port        "7000"
    bind_to_address "0.0.0.0"
    quality     "0"
    format      "44100:16:2"
}
```

debug output:
```
Starting program: /usr/bin/mpd --stdout --no-daemon --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
config_file: loading file /etc/mpd.conf
exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.3
sndfile: libsndfile-1.0.28
simple_db: reading DB
curl: version 7.62.0
curl: with OpenSSL/1.1.1
[New Thread 0x7fffe53f1700 (LWP 25624)]
[New Thread 0x7fffe4bf0700 (LWP 25625)]
avahi: Initializing interface
avahi: Client changed to state 101
avahi: Client is CONNECTING
state_file: Loading state file /var/lib/mpd/mpdstate
[New Thread 0x7fffe43ef700 (LWP 25626)]
[New Thread 0x7fffe3bee700 (LWP 25627)]
playlist: queue song 1:"堀江由衣 - The♡World's♡End (2014) [FLAC]/02 半永久的に愛してよ♡.flac"
decoder_thread: probing plugin flac
decoder: audio_format=44100:16:2, seekable=true
[New Thread 0x7fffe2fed700 (LWP 25628)]
output: opened "kirie radio (mp3)" (httpd) audio_format=44100:16:2
client: [0] opened from 10.17.1.10:56298
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "0""
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "decoders"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "outputs"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1

Thread 3 "rtio" received signal SIGSEGV, Segmentation fault.
```

`mpdstate`
```
sw_volume: 100
audio_device_state:1:kirie radio (mp3)
state: play
current: 0
time: 15.845000
random: 0
repeat: 0
single: 0
consume: 0
crossfade: 0
mixrampdb: 0.000000
mixrampdelay: -1.000000
playlist_begin
0:堀江由衣 - The♡World's♡End (2014) [FLAC]/01 The♡World's♡End.flac
playlist_end
```

P.S. I've been trying to get debugging symbols enabled but I'm not having luck (I spent about an hour messing around before opening this bug report). The following is modified from my distro's packaging environment, am I doing something wrong here?
```
env -i PATH="$PATH" meson setup \
  --prefix         /usr \
  --libdir         /usr/lib \
  --libexecdir     /usr/lib \
  --bindir         /usr/bin \
  --sbindir        /usr/bin \
  --includedir     /usr/include \
  --datadir        /usr/share \
  --mandir         /usr/share/man \
  --infodir        /usr/share/info \
  --localedir      /usr/share/locale \
  --sysconfdir     /etc \
  --localstatedir  /var \
  --sharedstatedir /var/lib \
  --buildtype      debug \
  --reconfigure \
  -D               b_ndebug=false \
  ${_pkgname} build \
  -Dsystemd=enabled \
  -Dsystemd_system_unit_dir=/usr/lib/systemd/system \
  -Dsystemd_user_unit_dir=/usr/lib/systemd/user

  ninja -C build
```

**Comment by lae** [comment]
Leave it to me to not bother trying to just build it manually (I was trying to package a debug build) - here's a backtrace:
```
Thread 3 "rtio" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe31ae700 (LWP 28095)]
0x0000555555686232 in AllocatedArray<unsigned char>::size (this=0x0) at ../../src/util/AllocatedArray.hxx:122
122                     return buffer.size;
(gdb) bt
#0  0x0000555555686232 in AllocatedArray<unsigned char>::size (this=0x0) at ../../src/util/AllocatedArray.hxx:122
#1  0x00005555556871ce in Page::GetSize (this=0x0) at ../../src/output/plugins/httpd/Page.hxx:46
#2  0x0000555555686cda in HttpdClient::TryWritePage (this=0x7fffcc000b20, page=..., position=0) at ../../src/output/plugins/httpd/HttpdClient.cxx:207
#3  0x00005555556873ff in HttpdClient::TryWrite (this=0x7fffcc000b20) at ../../src/output/plugins/httpd/HttpdClient.cxx:258
#4  0x0000555555687024 in HttpdClient::OnSocketReady (this=0x7fffcc000b20, flags=4) at ../../src/output/plugins/httpd/HttpdClient.cxx:380
#5  0x00005555555f01ee in SocketMonitor::Dispatch (this=0x7fffcc000b20, flags=4) at ../../src/event/SocketMonitor.cxx:37
#6  0x00005555555f5b06 in EventLoop::Run (this=0x555555867ad0) at ../../src/event/Loop.cxx:210
#7  0x00005555555f5066 in EventThread::Run (this=0x555555867ad0) at ../../src/event/Thread.cxx:57
#8  0x00005555555a8b90 in BindMethodDetail::BindMethodWrapperGenerator2<EventThread, void (EventThread::*)(), &EventThread::Run, void>::Invoke (_instance=0x555555867ad0) at ../../src/util/BindMethod.hxx:147
#9  0x00005555555efd9a in BoundMethod<void ()>::operator()() const (this=0x555555867c38) at ../../src/util/BindMethod.hxx:77
#10 0x00005555555faaf2 in Thread::Run (this=0x555555867c38) at ../../src/thread/Thread.cxx:64
#11 0x00005555555faad2 in Thread::ThreadProc (ctx=0x555555867c38) at ../../src/thread/Thread.cxx:93
#12 0x00007ffff4154a9d in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff0693b23 in clone () from /usr/lib/libc.so.6
```
