### ISSUE TITLE
MPD hangs when USB device power off, restart needed

### ISSUE THREAD

**Issue by sf666** [MusicPlayerDaemon/MPD#423]
Hi there,

I've discovered one annoying problem after upgrading to MPD 0.21.1 (using 0.20 before).

I an using mpd on an arch linux distribution. I use an Amplifier as external DAC (card 1).

```
# aplay -l

**** List of PLAYBACK Hardware Devices ****
card 0: SPDIF [Integrated SPDIF], device 0: S/PDIF PCM snd-soc-dummy-dai-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: Audio [McIntosh HD USB Audio], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 2: DWHDMI [DW-HDMI], device 0: DW HDMI [dw-hdmi-ahb-audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

```
after switching off the amplifier, the alsa audio device (card 1) is not available any more.

```aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: SPDIF [Integrated SPDIF], device 0: S/PDIF PCM snd-soc-dummy-dai-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 2: DWHDMI [DW-HDMI], device 0: DW HDMI [dw-hdmi-ahb-audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

at this moment MPD stops playing with this error message:

[code]exception: Failed to play on "MA 9000" (alsa): snd_pcm_writei() failed: Broken pipe
mpd: ../src/output/plugins/AlsaOutputPlugin.cxx:806: virtual void AlsaOutput::Cancel(): Assertion `period_buffer.IsEmpty()' failed.
[/code]

the new behaviour of mpd 0.21 is, that is refuses any incoming connection and is has to be restarted after the USB device is power on again.

```
ncmpcpp -> Connection refused
```

before upgrading to mpd 0.21 

 - I was still able to connect to the mpd daemon
 - I could power on the usb device (card 1 was available again) and send a play command to mpd so it was resuming playback from the last known song position.

Has anyone a hint how to fix it. for my setup the MPD daemon function is vital!

Cheers

SF

**Comment by MaxKellermann** [comment]
Need a backtrace!

**Comment by skidoo23** [comment]
Same issue here. MPD from master/git, Debian testing x64, external USB audio interface, ALSA. Disconnecting interface crashes MPD.

```
mpd.conf
audio_output {
        type            "alsa"
        name            "Lexicon Omega"
        device          "hw:Omega"
        mixer_type      "software"
}
```

```
# gdb --args mpd --stdout --no-daemon --verbose
GNU gdb (Debian 8.1-4+b1) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mpd...done.
(gdb) run
Starting program: /usr/local/bin/mpd --stdout --no-daemon --verbose
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
config_file: loading file /etc/mpd.conf
path: SetFSCharset: fs charset is:
soxr: soxr converter 'high'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.3-beta-36-g004ef8b
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
adplug: adplug 2.2.1
simple_db: reading DB
curl: version 7.61.0
curl: with GnuTLS/3.5.19
[New Thread 0x7fffe4e37700 (LWP 3498)]
[New Thread 0x7fffe4636700 (LWP 3499)]
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Initializing interface
avahi: Client changed to state 2
avahi: Client is RUNNING
avahi: Registering service _mpd._tcp/Music Player Daemon @ jukebox
avahi: Service group changed to state 0
avahi: Service group is UNCOMMITED
state_file: Loading state file /var/lib/mpd/state
[New Thread 0x7fffe3e35700 (LWP 3500)]
[New Thread 0x7fffe3634700 (LWP 3501)]
inotify: initializing inotify
decoder_thread: probing plugin mad
decoder: audio_format=48000:24:2, seekable=true
[New Thread 0x7fffe26b6700 (LWP 3502)]
exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
alsa_output: opened hw:Omega type=HW
alsa_output: buffer: size=96..174762 time=2000..3640875
alsa_output: period: size=48..87381 time=1000..1820438
alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
alsa_output: format=S24_3LE (Signed 24 bit Little Endian in 3bytes)
alsa_output: buffer_size=24000 period_size=6000
output: opened "Lexicon Omega" (alsa) audio_format=48000:24:2
inotify: watching music directory
avahi: Service group changed to state 1
avahi: Service group is REGISTERING
client: [0] opened from 192.168.24.105:58434
avahi: Service group changed to state 2
avahi: Service 'Music Player Daemon @ jukebox' successfully established.
(...)

Seperate USB audio interface from power.

exception: Failed to play on "Lexicon Omega" (alsa): snd_pcm_writei() failed: No such device
mpd: ../src/output/plugins/AlsaOutputPlugin.cxx:803: virtual void AlsaOutput::Cancel(): Assertion `period_buffer.IsEmpty()' failed.

Thread 6 "output:Lexicon " received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe26b6700 (LWP 3502)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x00007ffff0cb1f3b in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff0cb32f1 in __GI_abort () at abort.c:79
#2  0x00007ffff0caaa8a in __assert_fail_base (fmt=0x7ffff0dfeec8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5555556bbabc "period_buffer.IsEmpty()", file=file@entry=0x5555556bba90 "../src/output/plugins/AlsaOutputPlugin.cxx", line=line@entry=803, function=function@entry=0x5555556bbee0 <AlsaOutput::Cancel()::__PRETTY_FUNCTION__> "virtual void AlsaOutput::Cancel()") at assert.c:92
#3  0x00007ffff0caab02 in __GI___assert_fail (assertion=0x5555556bbabc "period_buffer.IsEmpty()", file=0x5555556bba90 "../src/output/plugins/AlsaOutputPlugin.cxx", line=803, function=0x5555556bbee0 <AlsaOutput::Cancel()::__PRETTY_FUNCTION__> "virtual void AlsaOutput::Cancel()") at assert.c:101
#4  0x000055555561fb78 in AlsaOutput::Cancel() (this=0x55555577e080)
    at ../src/output/plugins/AlsaOutputPlugin.cxx:803
#5  0x000055555560ff11 in FilteredAudioOutput::Cancel() (this=0x5555557d3f70) at ../src/output/Filtered.cxx:190
#6  0x000055555560fc6c in FilteredAudioOutput::CloseOutput(bool) (this=0x5555557d3f70, drain=false) at ../src/output/Filtered.cxx:135
#7  0x000055555560fdd9 in FilteredAudioOutput::Close(bool) (this=0x5555557d3f70, drain=false) at ../src/output/Filtered.cxx:157
#8  0x000055555561276c in AudioOutputControl::InternalClose(bool) (this=0x5555557d4200, drain=false) at ../src/output/Thread.cxx:192
#9  0x0000555555611eef in AudioOutputControl::InternalCloseError(std::__excep---Type <return> to continue, or q <return> to quit---
tion_ptr::exception_ptr) (this=0x5555557d4200, e=...)
    at ../src/output/Control.hxx:478
#10 0x0000555555612b17 in AudioOutputControl::PlayChunk() (this=0x5555557d4200) at ../src/output/Thread.cxx:273
#11 0x0000555555612c8f in AudioOutputControl::InternalPlay() (this=0x5555557d4200) at ../src/output/Thread.cxx:315
#12 0x00005555556119bb in AudioOutputControl::Task() (this=0x5555557d4200)
    at ../src/output/Thread.cxx:513
#13 0x000055555560d374 in BindMethodDetail::BindMethodWrapperGenerator2<AudioOutputControl, void (AudioOutputControl::*)(), &AudioOutputControl::Task, void>::Invoke(void*) (_instance=0x5555557d4200)
    at ../src/util/BindMethod.hxx:147
#14 0x00005555555d7152 in BoundMethod<void ()>::operator()() const (this=0x5555557d42a8) at ../src/util/BindMethod.hxx:77
#15 0x00005555555e07c8 in Thread::Run() (this=0x5555557d42a8)
    at ../src/thread/Thread.cxx:64
#16 0x00005555555e07a8 in Thread::ThreadProc(void*) (ctx=0x5555557d42a8)
    at ../src/thread/Thread.cxx:93
#17 0x00007ffff0e40f2a in start_thread (arg=0x7fffe26b6700)
    at pthread_create.c:463
#18 0x00007ffff0d73edf in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by MaxKellermann** [comment]
Thanks, I can reproduce the bug.
