### ISSUE TITLE
crash on song switch

### ISSUE THREAD

**Issue by installgentoo** [MusicPlayerDaemon/MPD#629]
### Describe the bug
Sometimes crashes when switching to new m4a file. Easy to get by spamming mpc -q next, can also happen on its own. Only started happening a few days ago.
```
# See the mpd.conf man page for a more detailed description of each parameter.
music_directory         "/_documents/music"
playlist_directory	"/var/lib/mpd/playlists"
db_file                 "/var/lib/mpd/database"
state_file              "/var/lib/mpd/state"
pid_file                "/var/lib/mpd/pid"
user                    "mpd"
auto_update             "yes"
#log_file               "/tmp/mpd_log"
#log_level              "verbose"

audio_output {
 type           "alsa"
 name           "My ALSA Device"
 auto_resample  "yes"
}

audio_output_format             "48000:24:2"

samplerate_converter            "soxr high"

volume_normalization            "yes"

filesystem_charset "UTF-8"

```
## Version
```
Music Player Daemon 0.21.13 (0.21.13)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple

Storage plugins:
 local


Decoders plugins:
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [pcm]

Filters:
 soxr

Tag plugins:


Output plugins:
 null alsa httpd

Encoder plugins:
 null lame wave

Input plugins:
 file alsa ffmpeg

Playlist plugins:
 extm3u m3u pls

Protocols:
 file:// alsa:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps://

Other features:
 epoll icu inotify tcp un

```

## Log
```
ffmpeg/aac: Input buffer exhausted before END element found
ffmpeg: avcodec_send_packet() failed: Invalid data found when processing input
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: stream 0, offset 0xda69: partial file
client: [94] closed
client: [95] opened from 127.0.0.1:33106
mpd: ../mpd-0.21.13/src/decoder/Control.cxx:126: void DecoderControl::Seek(SongTime): Assertion `state != DecoderState::START' failed.

Thread 4 "player" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff1b8a700 (LWP 28634)]
0x00007ffff5c12081 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5c12081 in raise () from /lib64/libc.so.6
#1  0x00007ffff5bfd525 in abort () from /lib64/libc.so.6
#2  0x00007ffff5bfd40f in ?? () from /lib64/libc.so.6
#3  0x00007ffff5c0acb3 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000004126dd in DecoderControl::Seek (this=<optimized out>, t=...) at ../mpd-0.21.13/src/decoder/Control.hxx:342
#5  0x000000000041a860 in Player::SeekDecoder (this=this@entry=0x7ffff1b89c20, seek_time=...) at ../mpd-0.21.13/src/Chrono.hxx:40
#6  0x000000000041cbf8 in Player::SeekDecoder (this=0x7ffff1b89c20) at ../mpd-0.21.13/src/player/Thread.cxx:666
#7  Player::ProcessCommand (this=0x7ffff1b89c20) at ../mpd-0.21.13/src/player/Thread.cxx:736
#8  Player::Run (this=this@entry=0x7ffff1b89c20) at ../mpd-0.21.13/src/player/Thread.cxx:985
#9  0x000000000041afd2 in do_play (pc=..., dc=..., buffer=...) at ../mpd-0.21.13/src/player/Thread.cxx:1136
#10 0x000000000041b112 in PlayerControl::RunThread (this=0x5013f0) at ../mpd-0.21.13/src/player/Thread.cxx:1161
#11 0x000000000041e8af in BindMethodDetail::BindMethodWrapperGenerator2<PlayerControl, void (PlayerControl::*)(), &PlayerControl::RunThread, void>::Invoke (
    _instance=<optimized out>) at ../mpd-0.21.13/src/util/BindMethod.hxx:145
#12 0x0000000000443603 in BoundMethod<void ()>::operator()() const (this=0x501418) at ../mpd-0.21.13/src/util/BindMethod.hxx:76
#13 Thread::Run (this=0x501418) at ../mpd-0.21.13/src/thread/Thread.cxx:63
#14 Thread::ThreadProc (ctx=0x501418) at ../mpd-0.21.13/src/thread/Thread.cxx:92
#15 0x00007ffff5d960c5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007ffff5ccfc0f in clone () from /lib64/libc.so.6
(gdb) 
```

**Comment by MaxKellermann** [comment]
I can reproduce this crash. Thanks for the excellent bug report!
