### ISSUE TITLE
SIGABRT on latest mpd build

### ISSUE THREAD

**Issue by ilyxa** [MusicPlayerDaemon/MPD#631]
### Describe the bug
any mpc command crashes mpd

## Expected Behavior
play/seek/etc

## Actual Behavior
`
(gdb) run
Starting program: /storarray/build/MPD/output/release/mpd --no-daemon --stderr -v /home/ilyxa/.config/mpd/mpd.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
config_file: loading file /home/ilyxa/.config/mpd/mpd.conf
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.3.1
sndfile: libsndfile-1.0.28
hybrid_dsd: The Hybrid DSD decoder is disabled because it was not explicitly enabled
exception: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
simple_db: reading DB
exception: Input plugin 'tidal' is not configured: No Tidal application token configured
exception: Input plugin 'qobuz' is not configured: No Qobuz app_id configured
curl: version 7.65.3
curl: with OpenSSL/1.1.1c
[New Thread 0x7fffe97c9700 (LWP 2715)]
[New Thread 0x7fffe8fc8700 (LWP 2716)]
state_file: Loading state file /home/ilyxa/.config/mpd/state
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
client: [0] opened from local
client: [0] process command list
client: process command "status"
exception: Failed to read mixer for 'PCM5102': failed to attach to hw:2: No such file or directory
client: command returned 0
client: process command "currentsong"
client: command returned 0
client: [0] process command list returned 0
mpd: ../../src/event/SocketMonitor.cxx:54: SocketDescriptor SocketMonitor::Steal(): Assertion `IsDefined()' failed.

Thread 1 "mpd" received signal SIGABRT, Aborted.
0x00007ffff218c755 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff218c755 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff2177851 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff2177727 in __assert_fail_base.cold () from /usr/lib/libc.so.6
#3  0x00007ffff2185026 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00005555555fa450 in SocketMonitor::Steal (this=0x555555932bf0) at ../../src/event/SocketMonitor.cxx:54
#5  0x00005555555fa4b9 in SocketMonitor::Close (this=0x555555932bf0) at ../../src/event/SocketMonitor.cxx:64
#6  0x00005555555a6224 in FullyBufferedSocket::Close (this=0x555555932bf0) at ../../src/event/FullyBufferedSocket.hxx:45
#7  0x00005555555a7bd1 in Client::Close (this=0x555555932bf0) at ../../src/client/New.cxx:85
#8  0x00005555555a6c7e in Client::OnTimeout (this=0x555555932bf0) at ../../src/client/Expire.cxx:47
#9  0x00005555555a8646 in BindMethodDetail::BindMethodWrapperGenerator2<Client, true, void (Client::*)() noexcept, &Client::OnTimeout, void>::Invoke(void*) (_instance=0x555555932bf0) at ../../src/util/BindMethod.hxx:189
#10 0x0000555555600a6a in BoundMethod<void () noexcept>::operator()() const (this=0x555555934c98) at ../../src/util/BindMethod.hxx:91
#11 0x0000555555600618 in TimerEvent::Run (this=0x555555934c70) at ../../src/event/TimerEvent.hxx:78
#12 0x000055555560097c in EventLoop::HandleTimers (this=0x7fffffffd968) at ../../src/event/Loop.cxx:125
#13 0x00005555555ffcca in EventLoop::Run (this=0x7fffffffd968) at ../../src/event/Loop.cxx:166
#14 0x0000555555589c17 in MainConfigured (options=..., raw_config=...) at ../../src/Main.cxx:547
#15 0x0000555555589eaa in MainOrThrow (argc=5, argv=0x7fffffffe278) at ../../src/Main.cxx:628
#16 0x0000555555589f53 in mpd_main (argc=5, argv=0x7fffffffe278) at ../../src/Main.cxx:636
#17 0x0000555555589fdb in main (argc=5, argv=0x7fffffffe278) at ../../src/Main.cxx:650
`

## Version
Music Player Daemon 0.22~git (v0.21.14-549-gf2cdbeace)

**Comment by ilyxa** [comment]
confirmed

**Comment by ilyxa** [comment]
build successful, mpd/mpc working as expected
