### ISSUE TITLE
MPD becomes unresponsive

### ISSUE THREAD

**Issue by vbabiy** [MusicPlayerDaemon/MPD#704]
### Describe the bug

When playing for a while, and then pausing for a few mins. MPD will become completely unresponsive or play a few seconds and then become unresponsive.

## Expected Behavior
No freeze

## Actual Behavior
Becoming Unresponsive, and in order to restart it I have to kill -9 it.

## Version
Manjaro Version:

```
mpd --version                                              
Music Player Daemon 0.21.18 (0.21.18)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

```

Source Version:

```
Music Player Daemon 0.21.18 (0.21.18)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

```
## Log
Last Log message:
```
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "replay_gain_status"
client: [0] command returned 0
client: [1] process command "idle"
client: [1] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "replay_gain_status"
client: [0] command returned 0
client: [1] process command "idle"
client: [1] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "seekid "3" "46""

```

Strace
```
> sudo strace  -f -p $(pidof mpd)                            
strace: Process 25521 attached with 7 threads
[pid 26112] restart_syscall(<... resuming interrupted read ...> <unfinished ...>
[pid 26111] futex(0x560cd249ac88, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26110] futex(0x7fa74ade89e4, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 26109] futex(0x560cd247c6b0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 25521] futex(0x560cd247c6e0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 25523] epoll_wait(8,  <unfinished ...>
[pid 25522] epoll_wait(6, 

^Cstrace: Process 25521 detached
strace: Process 25522 detached
 <detached ...>
strace: Process 25523 detached
strace: Process 26109 detached
strace: Process 26110 detached
strace: Process 26111 detached
strace: Process 26112 detached
```
gdb
```
> sudo gdb --pid=$(pidof mpd)                                
GNU gdb (GDB) 8.3.1
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 25521
[New LWP 25522]
[New LWP 25523]
[New LWP 26109]
[New LWP 26110]
[New LWP 26111]
[New LWP 26112]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fa75502ac45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
(gdb) thread apply all bt

Thread 7 (Thread 0x7fa749166700 (LWP 26112)):
#0  0x00007fa7533689ef in poll () from /usr/lib/libc.so.6
#1  0x00007fa755277c14 in ?? () from /usr/lib/libpulse.so.0
#2  0x00007fa755285059 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#3  0x00007fa75528f301 in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#4  0x00007fa75528f3b1 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#5  0x00007fa75527f61e in ?? () from /usr/lib/libpulse.so.0
#6  0x00007fa74d046d1c in ?? () from /usr/lib/pulseaudio/libpulsecommon-13.0.so
#7  0x00007fa7550244cf in start_thread () from /usr/lib/libpthread.so.0
#8  0x00007fa7533732d3 in clone () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7fa749967700 (LWP 26111)):
#0  0x00007fa75502ac45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000560cd11aa63e in PosixCond::wait (mutex=..., this=0x560cd249ac60) at ../../src/thread/PosixCond.hxx:74
#2  AudioOutputControl::Task (this=0x560cd249aba0) at ../../src/output/Thread.cxx:520
#3  0x0000560cd117e5fd in BoundMethod<void ()>::operator()() const (this=<optimized out>, this=<optimized out>) at ../../src/util/BindMethod.hxx:76
#4  Thread::Run (this=<optimized out>) at ../../src/thread/Thread.cxx:63
#5  Thread::ThreadProc (ctx=<optimized out>) at ../../src/thread/Thread.cxx:92
#6  0x00007fa7550244cf in start_thread () from /usr/lib/libpthread.so.0
#7  0x00007fa7533732d3 in clone () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7fa74a5e8700 (LWP 26110)):
#0  0x00007fa75502ac45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000560cd1154256 in PosixCond::wait (mutex=..., this=0x7fa74ade89b8) at ../../src/thread/PosixCond.hxx:74
#2  DecoderControl::Wait (this=0x7fa74ade8990) at ../../src/decoder/Control.hxx:225
#3  decoder_input_stream_open (uri=0x7fa7400011b0 "nfs://192.168.86.220/volume1/Media/Music/Library/Jeff Beck/Blow by Blow/01 You Know What I Mean.dsf", dc=...) at ../../src/decoder/Thread.cxx:72
#4  decoder_run_stream (uri=0x7fa7400011b0 "nfs://192.168.86.220/volume1/Media/Music/Library/Jeff Beck/Blow by Blow/01 You Know What I Mean.dsf", bridge=...) at ../../src/decoder/Thread.cxx:289
#5  DecoderUnlockedRunUri (path_fs=..., real_uri=0x7fa7400011b0 "nfs://192.168.86.220/volume1/Media/Music/Library/Jeff Beck/Blow by Blow/01 You Know What I Mean.dsf", bridge=...) at ../../src/decoder/Thread.cxx:423
#6  decoder_run_song (dc=..., song=..., uri=0x7fa7400011b0 "nfs://192.168.86.220/volume1/Media/Music/Library/Jeff Beck/Blow by Blow/01 You Know What I Mean.dsf", path_fs=...) at ../../src/decoder/Thread.cxx:484
#7  0x0000560cd1154490 in decoder_run (dc=...) at ../../src/decoder/Thread.cxx:527
#8  0x0000560cd115473c in DecoderControl::RunThread (this=0x7fa74ade8990) at ../../src/decoder/Thread.cxx:573
#9  0x0000560cd117e5fd in BoundMethod<void ()>::operator()() const (this=<optimized out>, this=<optimized out>) at ../../src/util/BindMethod.hxx:76
#10 Thread::Run (this=<optimized out>) at ../../src/thread/Thread.cxx:63
#11 Thread::ThreadProc (ctx=<optimized out>) at ../../src/thread/Thread.cxx:92
#12 0x00007fa7550244cf in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007fa7533732d3 in clone () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7fa74ade9700 (LWP 26109)):
#0  0x00007fa75502ac45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000560cd1154ac1 in PosixCond::wait (mutex=..., this=<optimized out>) at ../../src/thread/PosixCond.hxx:74
#2  DecoderControl::WaitForDecoder (this=0x7fa74ade8990) at ../../src/decoder/Control.cxx:47
#3  DecoderControl::Seek (this=0x7fa74ade8990, t=...) at ../../src/decoder/Control.cxx:160
#4  0x0000560cd115c0bc in Player::SeekDecoder (this=0x7fa74ade88e0, seek_time=...) at ../../src/Chrono.hxx:40
#5  0x0000560cd115d555 in Player::SeekDecoder (this=0x7fa74ade88e0) at ../../src/player/Thread.cxx:667
#6  Player::ProcessCommand (this=0x7fa74ade88e0) at ../../src/player/Thread.cxx:737
#7  Player::Run (this=this@entry=0x7fa74ade88e0) at ../../src/player/Thread.cxx:986
#8  0x0000560cd115c71b in do_play (buffer=..., dc=..., pc=...) at ../../src/player/Thread.cxx:1137
#9  PlayerControl::RunThread (this=0x560cd247c620) at ../../src/player/Thread.cxx:1162
#10 0x0000560cd117e5fd in BoundMethod<void ()>::operator()() const (this=<optimized out>, this=<optimized out>) at ../../src/util/BindMethod.hxx:76
#11 Thread::Run (this=<optimized out>) at ../../src/thread/Thread.cxx:63
#12 Thread::ThreadProc (ctx=<optimized out>) at ../../src/thread/Thread.cxx:92
#13 0x00007fa7550244cf in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007fa7533732d3 in clone () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7fa74b5ea700 (LWP 25523)):
--Type <RET> for more, q to quit, c to continue without paging--c
#0  0x00007fa75337360e in epoll_wait () from /usr/lib/libc.so.6
#1  0x0000560cd117e3d8 in EpollFD::Wait (timeout=<optimized out>, maxevents=16, events=0x560cd247d6d0, this=0x560cd247d6cc) at ../../src/system/FileDescriptor.hxx:99
#2  PollGroupEpoll::ReadEvents (timeout_ms=<optimized out>, result=..., this=0x560cd247d6cc) at ../../src/event/PollGroupEpoll.hxx:75
#3  EventLoop::Run (this=this@entry=0x560cd247d638) at ../../src/event/Loop.cxx:198
#4  0x0000560cd117d034 in EventThread::Run (this=0x560cd247d638) at ../../src/event/Thread.cxx:65
#5  0x0000560cd117e5fd in BoundMethod<void ()>::operator()() const (this=<optimized out>, this=<optimized out>) at ../../src/util/BindMethod.hxx:76
#6  Thread::Run (this=<optimized out>) at ../../src/thread/Thread.cxx:63
#7  Thread::ThreadProc (ctx=<optimized out>) at ../../src/thread/Thread.cxx:92
#8  0x00007fa7550244cf in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007fa7533732d3 in clone () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7fa74bdeb700 (LWP 25522)):
#0  0x00007fa75337360e in epoll_wait () from /usr/lib/libc.so.6
#1  0x0000560cd117e3d8 in EpollFD::Wait (timeout=<optimized out>, maxevents=16, events=0x560cd247d548, this=0x560cd247d544) at ../../src/system/FileDescriptor.hxx:99
#2  PollGroupEpoll::ReadEvents (timeout_ms=<optimized out>, result=..., this=0x560cd247d544) at ../../src/event/PollGroupEpoll.hxx:75
#3  EventLoop::Run (this=this@entry=0x560cd247d4b0) at ../../src/event/Loop.cxx:198
#4  0x0000560cd117d034 in EventThread::Run (this=0x560cd247d4b0) at ../../src/event/Thread.cxx:65
#5  0x0000560cd117e5fd in BoundMethod<void ()>::operator()() const (this=<optimized out>, this=<optimized out>) at ../../src/util/BindMethod.hxx:76
#6  Thread::Run (this=<optimized out>) at ../../src/thread/Thread.cxx:63
#7  Thread::ThreadProc (ctx=<optimized out>) at ../../src/thread/Thread.cxx:92
#8  0x00007fa7550244cf in start_thread () from /usr/lib/libpthread.so.0
#9  0x00007fa7533732d3 in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7fa74c1e25c0 (LWP 25521)):
#0  0x00007fa75502ac45 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
#1  0x0000560cd115eec3 in PosixCond::wait (mutex=..., this=0x560cd247c6b8) at ../../src/thread/PosixCond.hxx:74
#2  PlayerControl::ClientWait (this=0x560cd247c620) at ../../src/player/Control.hxx:397
#3  PlayerControl::WaitCommandLocked (this=<optimized out>) at ../../src/player/Control.hxx:444
#4  PlayerControl::SynchronousCommand (cmd=PlayerCommand::SEEK, this=0x560cd247c620) at ../../src/player/Control.hxx:459
#5  PlayerControl::SeekLocked (this=0x560cd247c620, song=..., t=...) at ../../src/player/Control.cxx:268
#6  0x0000560cd115f062 in PlayerControl::LockSeek (this=this@entry=0x560cd247c620, song=std::unique_ptr<DetachedSong> = {...}, t=t@entry=...) at /usr/include/c++/9.2.0/bits/move.h:74
#7  0x0000560cd1163dec in playlist::SeekSongOrder (this=0x560cd247c588, pc=..., i=<optimized out>, seek_time=...) at /usr/include/c++/9.2.0/bits/unique_ptr.h:153
#8  0x0000560cd1150b2d in Partition::SeekSongId (seek_time=..., song_id=3, this=<optimized out>) at ../../src/Partition.hxx:170
#9  handle_seekid (client=..., args=..., r=...) at ../../src/command/PlayerCommands.cxx:301
#10 0x0000560cd114f89b in command_process (client=..., num=num@entry=0, line=line@entry=0x560cd24d7f30 "seekid") at ../../src/command/AllCommands.cxx:418
#11 0x0000560cd1157301 in client_process_line (client=..., line=<optimized out>, line@entry=0x560cd24d7f30 "seekid") at ../../src/client/ClientProcess.cxx:133
#12 0x0000560cd1157460 in Client::OnSocketInput (this=0x560cd24d7f00, data=0x560cd24d7f30, length=<optimized out>) at ../../src/client/ClientRead.cxx:46
#13 0x0000560cd117bc6e in BufferedSocket::ResumeInput (this=0x560cd24d7f00) at ../../src/event/BufferedSocket.cxx:76
#14 0x0000560cd117bdc8 in BufferedSocket::OnSocketReady (this=0x560cd24d7f00, flags=<optimized out>) at ../../src/event/BufferedSocket.cxx:113
#15 0x0000560cd117e451 in EventLoop::Run (this=0x560cd247d338) at ../../src/event/Loop.cxx:215
#16 0x0000560cd114e7d2 in mpd_main_after_fork (config=..., raw_config=...) at ../../src/Main.cxx:600
#17 MainOrThrow (argc=<optimized out>, argv=<optimized out>) at ../../src/Main.cxx:476
#18 0x0000560cd114ed4b in mpd_main (argc=<optimized out>, argv=<optimized out>) at ../../src/Main.cxx:487
#19 0x00007fa75329b153 in __libc_start_main () from /usr/lib/libc.so.6
#20 0x0000560cd114deae in _start () at ../../src/Main.cxx:382
```
Config
```
# An example configuration file for MPD.
# Read the user manual for documentation: http://www.musicpd.org/doc/user/


# Files and directories #######################################################
#
# This setting controls the top directory which MPD will search to discover the
# available audio files and add them to the daemon's online database. This 
# setting defaults to the XDG directory, otherwise the music directory will be
# be disabled and audio files will only be accepted over ipc socket (using
# file:// protocol) or streaming files over an accepted protocol.
#
#music_directory		"~/music"
music_directory		"nfs://192.168.86.220/volume1/Media/Music/Library"
#
# This setting sets the MPD internal playlist directory. The purpose of this
# directory is storage for playlists created by MPD. The server will use 
# playlist files not created by the server but only if they are in the MPD
# format. This setting defaults to playlist saving being disabled.
#
playlist_directory		"~/.mpd/playlists"
#
# This setting sets the location of the MPD database. This file is used to
# load the database at server start up and store the database while the 
# server is not up. This setting defaults to disabled which will allow
# MPD to accept files over ipc socket (using file:// protocol) or streaming
# files over an accepted protocol.
#
#db_file			"~/.mpd/database"
# 
# These settings are the locations for the daemon log files for the daemon.
# These logs are great for troubleshooting, depending on your log_level
# settings.
#
# The special value "syslog" makes MPD use the local syslog daemon. This
# setting defaults to logging to syslog.
#
#log_file			"~/.mpd/log"
#
# This setting sets the location of the file which stores the process ID
# for use of mpd --kill and some init scripts. This setting is disabled by
# default and the pid file will not be stored.
#
#pid_file			"~/.mpd/pid"
#
# This setting sets the location of the file which contains information about
# most variables to get MPD back into the same general shape it was in before
# it was brought down. This setting is disabled by default and the server 
# state will be reset on server start up.
#
#state_file			"~/.mpd/state"
#
# The location of the sticker database.  This is a database which
# manages dynamic information attached to songs.
#
#sticker_file			"~/.mpd/sticker.sql"
#
###############################################################################


# General music daemon options ################################################
#
# This setting specifies the user that MPD will run as. MPD should never run as
# root and you may use this setting to make MPD change its user ID after
# initialization. This setting is disabled by default and MPD is run as the
# current user.
#
#user				"nobody"
#
# This setting specifies the group that MPD will run as. If not specified
# primary group of user specified with "user" setting will be used (if set).
# This is useful if MPD needs to be a member of group such as "audio" to
# have permission to use sound card.
#
#group				"nogroup"
#
# This setting sets the address for the daemon to listen on. Careful attention
# should be paid if this is assigned to anything other then the default, any.
# This setting can deny access to control of the daemon. Not effective if
# systemd socket activiation is in use.
#
# For network
bind_to_address		"0.0.0.0"
#
# And for Unix Socket
#bind_to_address		"~/.mpd/socket"
#
# This setting is the TCP port that is desired for the daemon to get assigned
# to.
#
port				"6600"
#
# This setting controls the type of information which is logged. Available 
# setting arguments are "default", "secure" or "verbose". The "verbose" setting
# argument is recommended for troubleshooting, though can quickly stretch
# available resources on limited hardware storage.
#
log_level			"verbose"
#
# Setting "restore_paused" to "yes" puts MPD into pause mode instead
# of starting playback after startup.
#
#restore_paused "no"
#
# This setting enables MPD to create playlists in a format usable by other
# music players.
#
#save_absolute_paths_in_playlists	"no"
#
# This setting defines a list of tag types that will be extracted during the
# audio file discovery process. The complete list of possible values can be
# found in the user manual.
#metadata_to_use	"artist,album,title,track,name,genre,date,composer,performer,disc"
#
# This example just enables the "comment" tag without disabling all
# the other supported tags:
#metadata_to_use "+comment"
#
# This setting enables automatic update of MPD's database when files in 
# music_directory are changed.
#
#auto_update	"yes"
auto_update	"no"
#
# Limit the depth of the directories being watched, 0 means only watch
# the music directory itself.  There is no limit by default.
#
#auto_update_depth "3"
#
###############################################################################


# Symbolic link behavior ######################################################
#
# If this setting is set to "yes", MPD will discover audio files by following 
# symbolic links outside of the configured music_directory.
#
#follow_outside_symlinks	"yes"
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links inside of the configured music_directory.
#
#follow_inside_symlinks		"yes"
#
###############################################################################


# Zeroconf / Avahi Service Discovery ##########################################
#
# If this setting is set to "yes", service information will be published with
# Zeroconf / Avahi.
#
zeroconf_enabled		"yes"
#
# The argument to this setting will be the Zeroconf / Avahi unique name for
# this MPD server on the network. %h will be replaced with the hostname.
#
zeroconf_name			"Office"
#
###############################################################################


# Permissions #################################################################
#
# If this setting is set, MPD will require password authorization. The password
# setting can be specified multiple times for different password profiles.
#
#password                        "password@read,add,control,admin"
#
# This setting specifies the permissions a user has who has not yet logged in. 
#
#default_permissions             "read,add,control,admin"
#
###############################################################################


# Database #######################################################################
#

database {
       plugin "proxy"
       host "mpd.local"
       port "6600"
}

# Input #######################################################################
#

input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

#
###############################################################################

# Audio Output ################################################################
#
# MPD supports various audio output types, as well as playing through multiple 
# audio outputs at the same time, through multiple audio_output settings 
# blocks. Setting this block is optional, though the server will only attempt
# autodetection for one sound card.
#
# An example of an ALSA output:
#
#audio_output {
#	type		"alsa"
#	name		"My ALSA Device"
##	device		"hw:0,0"	# optional
##	mixer_type      "hardware"	# optional
##	mixer_device	"default"	# optional
##	mixer_control	"PCM"		# optional
##	mixer_index	"0"		# optional
#}
#
# An example of an OSS output:
#
#audio_output {
#	type		"oss"
#	name		"My OSS Device"
##	device		"/dev/dsp"	# optional
##	mixer_type      "hardware"	# optional
##	mixer_device	"/dev/mixer"	# optional
##	mixer_control	"PCM"		# optional
#}
#
# An example of a shout output (for streaming to Icecast):
#
#audio_output {
#	type		"shout"
#	encoder		"vorbis"		# optional
#	name		"My Shout Stream"
#	host		"localhost"
#	port		"8000"
#	mount		"/mpd.ogg"
#	password	"hackme"
#	quality		"5.0"
#	bitrate		"128"
#	format		"44100:16:1"
##	protocol	"icecast2"		# optional
##	user		"source"		# optional
##	description	"My Stream Description"	# optional
##	url		"http://example.com"	# optional
##	genre		"jazz"			# optional
##	public		"no"			# optional
##	timeout		"2"			# optional
##	mixer_type      "software"		# optional
#}
#
# An example of a recorder output:
#
#audio_output {
#	type		"recorder"
#	name		"My recorder"
#	encoder		"vorbis"		# optional, vorbis or lame
#	path		"/var/lib/mpd/recorder/mpd.ogg"
##	quality		"5.0"			# do not define if bitrate is defined
#	bitrate		"128"			# do not define if quality is defined
#	format		"44100:16:1"
#}
#
# An example of a httpd output (built-in HTTP streaming server):
#
#audio_output {
#	type		"httpd"
#	name		"My HTTP Stream"
#	encoder		"vorbis"		# optional, vorbis or lame
#	port		"8000"
#	bind_to_address	"0.0.0.0"		# optional, IPv4 or IPv6
##	quality		"5.0"			# do not define if bitrate is defined
#	bitrate		"128"			# do not define if quality is defined
#	format		"44100:16:1"
#	max_clients	"0"			# optional 0=no limit
#}
#
# An example of a pulseaudio output (streaming to a remote pulseaudio server)
#
audio_output {
	type		"pulse"
	name		"My Pulse Output"
	auto_format	"yes"
##	server		"remote_server"		# optional
##	sink		"remote_server_sink"	# optional
}
#
# An example of a winmm output (Windows multimedia API).
#
#audio_output {
#	type		"winmm"
#	name		"My WinMM output"
##	device		"Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#		or
##	device		"0"		# optional
##	mixer_type	"hardware"	# optional
#}
#
# An example of an openal output.
#
#audio_output {
#	type		"openal"
#	name		"My OpenAL output"
##	device		"Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#}
#
# An example of an sndio output.
#
#audio_output {
#	type		"sndio"
#	name		"sndio output"
#	mixer_type	"hardware"
#}
#
# An example of an OS X output:
#
#audio_output {
#	type		"osx"
#	name		"My OS X Device"
##	device		"Built-in Output"	# optional
##	channel_map      "-1,-1,0,1"	# optional
#}
#
## Example "pipe" output:
#
#audio_output {
#	type		"pipe"
#	name		"my pipe"
#	command		"aplay -f cd 2>/dev/null"
## Or if you're want to use AudioCompress
#	command		"AudioCompress -m | aplay -f cd 2>/dev/null"
## Or to send raw PCM stream through PCM:
#	command		"nc example.org 8765"
#	format		"44100:16:2"
#}
#
## An example of a null output (for no audio output):
#
#audio_output {
#	type		"null"
#	name		"My Null Output"
#	mixer_type      "none"			# optional
#}
#
###############################################################################


# Normalization automatic volume adjustments ##################################
#
# This setting specifies the type of ReplayGain to use. This setting can have
# the argument "off", "album", "track" or "auto". "auto" is a special mode that
# chooses between "track" and "album" depending on the current state of
# random playback. If random playback is enabled then "track" mode is used.
# See <http://www.replaygain.org> for more details about ReplayGain.
# This setting is off by default.
#
#replaygain			"album"
#
# This setting sets the pre-amp used for files that have ReplayGain tags. By
# default this setting is disabled.
#
#replaygain_preamp		"0"
#
# This setting sets the pre-amp used for files that do NOT have ReplayGain tags.
# By default this setting is disabled.
#
#replaygain_missing_preamp	"0"
#
# This setting enables or disables ReplayGain limiting.
# MPD calculates actual amplification based on the ReplayGain tags
# and replaygain_preamp / replaygain_missing_preamp setting.
# If replaygain_limit is enabled MPD will never amplify audio signal
# above its original level. If replaygain_limit is disabled such amplification
# might occur. By default this setting is enabled.
#
#replaygain_limit		"yes"
#
# This setting enables on-the-fly normalization volume adjustment. This will
# result in the volume of all playing audio to be adjusted so the output has 
# equal "loudness". This setting is disabled by default.
#
#volume_normalization		"no"
#
###############################################################################

# Character Encoding ##########################################################
#
# If file or directory names do not display correctly for your locale then you 
# may need to modify this setting.
#
#filesystem_charset		"UTF-8"
#
###############################################################################
```

**Comment by MaxKellermann** [comment]
MPD is waiting for your NFS server. Please check if there is a problem with the NFS connection.

**Comment by vbabiy** [comment]
I moved to using a mount point, and now I am having no issues. Thanks @MaxKellermann going to close the ticket. 

Just an FYI, I am using a Synology NAS. I didn't see much in the logs there.
