### ISSUE TITLE
deadlock with NFS input (Android)

### ISSUE THREAD

**Issue by tguillem** [MusicPlayerDaemon/MPD#806]
### Describe the bug

MPD deadlock few minutes or hours after playing and stopping a file.

Reproduce steps:
 - Play a file, album, playlist from a NFS share (it won't deadlock untill MPD is playing)
 - Pause it, disconnect your client
 - Wait minutes, likely hours
 - Connect to the server again, play an other file/album/directory
 - No response from the server

I don't think the issue is specific to Android.
No problem with the same build using a music db from a http server.

## Expected Behavior
No deadlock, the client should be able to play an other file after the first session.

## Actual Behavior
Deadlocking.

## Version
Own armv8 Android build from master tree (1ec283d213986ef77aaa77f2e175a8b48615eb9b)

## Log
Here are the gdb backtraces (logs are not useful):
```
Thread 19 (Thread 17111.17150):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270fee31c0 in __futex_wait_ex(void volatile*, bool, int, bool, timespec const*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x000000270ff41ec0 in pthread_cond_wait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#3  0x00000027ab768334 in std::__ndk1::__libcpp_condvar_wait (__cv=0x279c4578a0, __m=0x89) at /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/__threading_support:295
#4  std::__ndk1::condition_variable::wait (this=0x279c4578a0, lk=...) at /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/condition_variable.cpp:44
#5  0x00000027ab4d4c58 in AudioOutputControl::Task (this=0x279c4577c0) at ../src/output/Thread.cxx:520
#6  0x00000027ab4babb0 in BoundMethod<void () noexcept>::operator()() const (this=<optimized out>) at ../src/util/BindMethod.hxx:91
#7  Thread::Run (this=<optimized out>) at ../src/thread/Thread.cxx:63
#8  Thread::ThreadProc (ctx=0x279c457880) at ../src/thread/Thread.cxx:92
#9  0x000000270ff4297c in __pthread_start(void*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#10 0x000000270fee44bc in __start_thread () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so

Thread 18 (Thread 17111.17149):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270fee31c0 in __futex_wait_ex(void volatile*, bool, int, bool, timespec const*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x000000270ff41ec0 in pthread_cond_wait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#3  0x00000027ab768334 in std::__ndk1::__libcpp_condvar_wait (__cv=0x27abf9d2a8, __m=0x89) at /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/__threading_support:295
#4  std::__ndk1::condition_variable::wait (this=0x27abf9d2a8, lk=...) at /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/condition_variable.cpp:44
#5  0x00000027ab4951f8 in DecoderBridge::OpenUri (this=0x27ad4fcf00, uri=<optimized out>) at ../src/decoder/Bridge.cxx:399
#6  0x00000027ab492d34 in decoder_run_stream (bridge=..., uri=<optimized out>) at ../src/decoder/Thread.cxx:251
#7  DecoderUnlockedRunUri (bridge=..., real_uri=<optimized out>, path_fs=...) at ../src/decoder/Thread.cxx:386
#8  decoder_run_song (dc=..., song=..., uri=<optimized out>, path_fs=...) at ../src/decoder/Thread.cxx:446
#9  decoder_run (dc=...) at ../src/decoder/Thread.cxx:487
#10 0x00000027ab492900 in DecoderControl::RunThread (this=0x27abf9d270) at ../src/decoder/Thread.cxx:512
#11 0x00000027ab4babb0 in BoundMethod<void () noexcept>::operator()() const (this=<optimized out>) at ../src/util/BindMethod.hxx:91
#12 Thread::Run (this=<optimized out>) at ../src/thread/Thread.cxx:63
#13 Thread::ThreadProc (ctx=0x27abf9d278) at ../src/thread/Thread.cxx:92
#14 0x000000270ff4297c in __pthread_start(void*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#15 0x000000270fee44bc in __start_thread () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so

Thread 17 (Thread 17111.17148):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270fee31c0 in __futex_wait_ex(void volatile*, bool, int, bool, timespec const*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x000000270ff41ec0 in pthread_cond_wait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#3  0x00000027ab768334 in std::__ndk1::__libcpp_condvar_wait (__cv=0x27926903f8, __m=0x89) at /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/__threading_support:295
#4  std::__ndk1::condition_variable::wait (this=0x27926903f8, lk=...) at /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/condition_variable.cpp:44
#5  0x00000027ab49cb04 in DecoderControl::WaitForDecoder (this=0x62, lock=...) at ../src/decoder/Control.hxx:218
#6  Player::CheckDecoderStartup (this=0x27abf9d3b8, lock=...) at ../src/player/Thread.cxx:569
#7  0x00000027ab49c330 in Player::Run (this=0x27abf9d3b8) at ../src/player/Thread.cxx:993
#8  0x00000027ab49bea8 in do_play (pc=..., dc=..., buffer=...) at ../src/player/Thread.cxx:1140
#9  PlayerControl::RunThread (this=0x2792690380) at ../src/player/Thread.cxx:1166
#10 0x00000027ab4babb0 in BoundMethod<void () noexcept>::operator()() const (this=<optimized out>) at ../src/util/BindMethod.hxx:91
#11 Thread::Run (this=<optimized out>) at ../src/thread/Thread.cxx:63
#12 Thread::ThreadProc (ctx=0x27926903b0) at ../src/thread/Thread.cxx:92
#13 0x000000270ff4297c in __pthread_start(void*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#14 0x000000270fee44bc in __start_thread () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so

Thread 16 (Thread 17111.17147):
#0  0x000000270ff2f09c in __epoll_pwait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x00000027ab4ba130 in EpollFD::Wait (this=<optimized out>, events=0x27ab3f7f70, maxevents=16, timeout=-1) at ../src/system/EpollFD.hxx:55
#2  0x00000027ab4b9d30 in PollGroupEpoll::ReadEvents (this=0x27ab3f7f6c, result=..., timeout_ms=-1) at ../src/event/PollGroupEpoll.hxx:75
#3  EventLoop::Run (this=0x27ab3f7ed8) at ../src/event/Loop.cxx:198
#4  0x00000027ab4b9444 in EventThread::Run (this=0x27ab3f7ed8) at ../src/event/Thread.cxx:65
#5  0x00000027ab4babb0 in BoundMethod<void () noexcept>::operator()() const (this=<optimized out>) at ../src/util/BindMethod.hxx:91
#6  Thread::Run (this=<optimized out>) at ../src/thread/Thread.cxx:63
#7  Thread::ThreadProc (ctx=0x27ab3f8080) at ../src/thread/Thread.cxx:92
#8  0x000000270ff4297c in __pthread_start(void*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#9  0x000000270fee44bc in __start_thread () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so

Thread 15 (Thread 17111.17146):
#0  0x000000270ff2f09c in __epoll_pwait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
--Type <RET> for more, q to quit, c to continue without paging--
#1  0x00000027ab4ba130 in EpollFD::Wait (this=<optimized out>, events=0x27ab3f7da0, maxevents=16, timeout=-1) at ../src/system/EpollFD.hxx:55
#2  0x00000027ab4b9d30 in PollGroupEpoll::ReadEvents (this=0x27ab3f7d9c, result=..., timeout_ms=-1) at ../src/event/PollGroupEpoll.hxx:75
#3  EventLoop::Run (this=0x27ab3f7d08) at ../src/event/Loop.cxx:198
#4  0x00000027ab4b9444 in EventThread::Run (this=0x27ab3f7d08) at ../src/event/Thread.cxx:65
#5  0x00000027ab4babb0 in BoundMethod<void () noexcept>::operator()() const (this=<optimized out>) at ../src/util/BindMethod.hxx:91
#6  Thread::Run (this=<optimized out>) at ../src/thread/Thread.cxx:63
#7  Thread::ThreadProc (ctx=0x27ab3f7eb0) at ../src/thread/Thread.cxx:92
#8  0x000000270ff4297c in __pthread_start(void*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#9  0x000000270fee44bc in __start_thread () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so

Thread 14 (Thread 17111.17143):
#0  0x000000270ff2f09c in __epoll_pwait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270e4d7f00 in ?? ()
#2  0x00000000746bbb9b in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

Thread 13 (Thread 17111.17142):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270fee31c0 in __futex_wait_ex(void volatile*, bool, int, bool, timespec const*) () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x000000270ff41ec0 in pthread_cond_wait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#3  0x00000027ab768334 in std::__ndk1::__libcpp_condvar_wait (__cv=0x2792690428, __m=0x89) at /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/include/__threading_support:295
#4  std::__ndk1::condition_variable::wait (this=0x2792690428, lk=...) at /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/src/condition_variable.cpp:44
#5  0x00000027ab49e0a8 in PlayerControl::SeekLocked (this=0x2792690380, lock=..., song=..., t=...) at ../src/player/Control.cxx:279
#6  0x00000027ab49df48 in PlayerControl::Play (this=0x2792690380, song=...) at ../src/player/Control.cxx:70
#7  0x00000027ab4a3664 in playlist::PlayOrder (this=0x27926902e0, pc=..., order=<optimized out>) at ../src/queue/Playlist.cxx:185
#8  0x00000027ab48e2a4 in Partition::PlayPosition (this=0x62, position=220) at ../src/Partition.hxx:179
#9  handle_play (client=..., args=..., r=...) at ../src/command/PlayerCommands.cxx:66
#10 0x00000027ab48d06c in command_process (client=..., num=<optimized out>, line=<optimized out>) at ../src/command/AllCommands.cxx:426
#11 0x00000027ab496c28 in Client::ProcessLine (this=0x2792469800, line=0x2792469830 "play") at ../src/client/Process.cxx:139
#12 0x00000027ab496fec in Client::OnSocketInput (this=0x2792469800, data=0x2792469830, length=<optimized out>) at ../src/client/Read.cxx:49
#13 0x00000027ab4b7e98 in BufferedSocket::ResumeInput (this=0x2792469800) at ../src/event/BufferedSocket.cxx:76
#14 0x00000027ab4b7fc4 in BufferedSocket::OnSocketReady (this=0x2792469800, flags=<optimized out>) at ../src/event/BufferedSocket.cxx:113
#15 0x00000027ab4b9d84 in EventLoop::Run (this=0x27ab3f7b58) at ../src/event/Loop.cxx:215
#16 0x00000027ab48aebc in MainConfigured (options=..., raw_config=...) at ../src/Main.cxx:532
#17 AndroidMain () at ../src/Main.cxx:563
#18 Java_org_musicpd_Bridge_run (env=0x27924ef920, _context=<optimized out>, _logListener=<optimized out>) at ../src/Main.cxx:584
#19 0x0000002792d37be4 in ?? ()
#20 0x00000027ab3f9000 in ?? ()
Backtrace stopped: not enough registers or memory available to unwind further

Thread 12 (Thread 17111.17127):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x00000027928b1250 in ?? ()
#2  0x000000000009c400 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 11 (Thread 17111.17126):
#0  0x000000270ff2f188 in __ioctl () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270feea114 in ioctl () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x00000027108075e8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 10 (Thread 17111.17125):
#0  0x000000270ff2f188 in __ioctl () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270feea114 in ioctl () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x00000027108075e8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 9 (Thread 17111.17124):
#0  0x000000270ff2f188 in __ioctl () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270feea114 in ioctl () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x00000027108075e8 in ?? ()
#3  0x0000000000000001 in ?? () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/bin/app_process64
--Type <RET> for more, q to quit, c to continue without paging--
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 8 (Thread 17111.17123):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x00000027928b1250 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 7 (Thread 17111.17122):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x00000027928b1250 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 6 (Thread 17111.17121):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x00000027928b1250 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 5 (Thread 17111.17120):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x00000027928b1250 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 17111.17119):
#0  0x000000270ff2f1b8 in __ppoll () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270feec5f0 in poll () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x0000002791f65c54 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 17111.17118):
#0  0x000000270ff2f27c in __rt_sigtimedwait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270feee94c in sigwait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#2  0x0000002792c56c9c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 17111.17117):
#0  0x000000270fee006c in syscall () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x00000027928b1250 in ?? ()
#2  0x0000002792c83190 in ?? ()
#3  0x0000002798c6d588 in ?? ()
Backtrace stopped: not enough registers or memory available to unwind further

Thread 1 (Thread 17111.17111):
#0  0x000000270ff2f09c in __epoll_pwait () from /home/tom/work/git/mpd/build-android/gdb/obj/local/arm64-v8a/system/lib64/libc.so
#1  0x000000270e4d7f00 in ?? ()
#2  0x00000000746bbb9b in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

**Comment by anwyn** [comment]
This does not only happen in Android, see #756
