### ISSUE TITLE
Build errors: <path> is dirty ... FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by nousernouser** [MusicPlayerDaemon/MPD#815]
## Bug report

Build error (meson-install): 
`<path> is dirty ... FileNotFoundError: [Errno 2] No such file or directory`

System: Debian (Devuan) stable, amd64
Meson:  0.54.0.rc1 (same errors with 0.52 and 0.49.2)
Ninja: 1.8.2
Boost: 1.71

MPD sources: 0.21.21 (master at #cfa4524) 

### Describe the bug

With: 
~~~
$ meson . output/release --buildtype=debugoptimized -Db_ndebug=true -Dprefix=/usr -Ddocumentation=true -Dchromaprint=disabled -Dipv6=disabled -Dlame=disabled -Dpulse=disabled -Dqobuz=disabled -Dshine=disabled -Dshout=disabled -Dsidplay=disabled -Dsmbclient=disabled -Dsndio=disabled -Dsoundcloud=disabled -Dsystemd=disabled -Dtidal=disabled -Dtwolame=disabled -Dzeroconf=disabled
~~~
I have:
~~~
Build type: native build
Project name: mpd
Project version: 0.22~git
C compiler for the host machine: ccache cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
C linker for the host machine: cc ld.bfd 2.31.1
C++ compiler for the host machine: ccache c++ (gcc 8.3.0 "c++ (Debian 8.3.0-6) 8.3.0")
C++ linker for the host machine: c++ ld.bfd 2.31.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wall: YES 
Compiler for C++ supports arguments -Wextra: YES 
Compiler for C++ supports arguments -Wvla: YES 
Compiler for C++ supports arguments -fvisibility=hidden: YES 
Compiler for C++ supports arguments -ffast-math: YES 
Compiler for C++ supports arguments -ftree-vectorize: YES 
Compiler for C++ supports arguments -fno-threadsafe-statics: YES 
Compiler for C++ supports arguments -fmerge-all-constants: YES 
Compiler for C++ supports arguments -Wmissing-declarations: YES 
Compiler for C++ supports arguments -Wshadow: YES 
Compiler for C++ supports arguments -Wpointer-arith: YES 
Compiler for C++ supports arguments -Wcast-qual: YES 
Compiler for C++ supports arguments -Wwrite-strings: YES 
Compiler for C++ supports arguments -Wsign-compare: YES 
Compiler for C++ supports arguments -Wcomma: NO 
Compiler for C++ supports arguments -Wextra-semi: YES 
Compiler for C++ supports arguments -Wheader-hygiene: NO 
Compiler for C++ supports arguments -Winconsistent-missing-destructor-override: NO 
Compiler for C++ supports arguments -Wunreachable-code-break: NO 
Compiler for C++ supports arguments -Wunused: YES 
Compiler for C++ supports arguments -Wused-but-marked-unused: NO 
Compiler for C++ supports arguments -Wno-non-virtual-dtor -Wnon-virtual-dtor: YES 
Compiler for C++ supports arguments -Wno-noexcept-type -Wnoexcept-type: YES 
Compiler for C++ supports arguments -ffunction-sections: YES 
Compiler for C++ supports arguments -fdata-sections: YES 
meson.build:113: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
meson.build:113: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Compiler for C supports arguments -Wall: YES 
Compiler for C supports arguments -Wextra: YES 
Compiler for C supports arguments -Wvla: YES 
Compiler for C supports arguments -fvisibility=hidden: YES 
Compiler for C supports arguments -ffast-math: YES 
Compiler for C supports arguments -ftree-vectorize: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wcast-qual: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Compiler for C supports arguments -pedantic: YES 
Compiler for C supports arguments -ffunction-sections: YES 
Compiler for C supports arguments -fdata-sections: YES 
meson.build:114: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
meson.build:114: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Compiler for C++ supports link arguments -Wl,--gc-sections: YES 
Has header "locale.h" : YES 
Checking for function "getpwnam_r" : YES 
Checking for function "getpwuid_r" : YES 
Checking for function "initgroups" : YES 
Checking for function "fnmatch" : YES 
Checking for function "strndup" : YES 
Checking for function "strcasestr" : YES 
Checking for function "syslog" : YES 
Run-time dependency Boost found: YES 1.71.0 (/usr/include)
Run-time dependency threads found: YES
Checking for function "pthread_setname_np" with dependency threads: YES 
Found pkg-config: /usr/bin/pkg-config (0.29)
Run-time dependency dbus-1 found: YES 1.12.16
Run-time dependency icu-i18n found: YES 63.1
Dependency smbclient skipped: feature smbclient disabled
Run-time dependency zlib found: YES 1.2.11
Run-time dependency alsa found: YES 1.1.8
Dependency libchromaprint skipped: feature chromaprint disabled
Run-time dependency libcurl found: YES 7.64.0
Run-time dependency expat found: YES 2.2.6
Run-time dependency libavformat found: YES 58.20.100
Run-time dependency libavcodec found: YES 58.35.100
Run-time dependency libavutil found: YES 56.22.100
Run-time dependency libavfilter found: YES 7.40.101
Run-time dependency libnfs found: YES 3.0.0
Run-time dependency libpcre found: YES 8.39
Dependency libpulse skipped: feature pulse disabled
Library sndio skipped: feature sndio disabled
Run-time dependency sqlite3 found: YES 3.27.2
Dependency libsystemd skipped: feature systemd disabled
Run-time dependency libupnp found: YES 1.8.4
Run-time dependency yajl found: YES 2.1.0
Header <sys/socket.h> has symbol "struct ucred" : YES 
Header <sys/socket.h> has symbol "SO_PEERCRED" : YES 
Checking for function "getpeereid" : NO 
Run-time dependency id3tag found: YES 0.15.0b
Run-time dependency samplerate found: YES 0.1.9
Run-time dependency soxr found: YES 0.1.2
Run-time dependency libcdio_paranoia found: YES 10.2+0.94+2
Run-time dependency libmms found: YES 0.6.4
Run-time dependency libiso9660 found: YES 2.0.0
Library bz2 found: YES
Run-time dependency zziplib found: YES 0.13.62
Run-time dependency ao found: YES 1.2.2
Run-time dependency jack found: YES 1.9.12
Header <jack/jack.h> has symbol "jack_set_info_function" : YES 
Run-time dependency openal found: YES 1.19.1
Dependency shout skipped: feature shout disabled
Run-time dependency flac found: YES 1.3.2
Run-time dependency opus found: YES 1.3
Run-time dependency vorbis found: YES 1.3.6
Run-time dependency vorbisenc found: YES 1.3.6
Run-time dependency ogg found: YES 1.3.2
Run-time dependency adplug found: YES 2.2.1
Run-time dependency fluidsynth found: YES 1.1.11
Run-time dependency audiofile found: YES 0.3.6
Library faad found: YES
Library gme found: YES
Library mad found: YES
Run-time dependency libmikmod found: YES 3.3.11
Run-time dependency libmodplug found: YES 0.8.9.0
Library mpcdec found: YES
Run-time dependency libmpg123 found: YES 1.25.10
Run-time dependency sndfile found: YES 1.0.28
Run-time dependency wavpack found: YES 5.1.0
Library WildMidi found: YES
Library mp3lame skipped: feature lame disabled
Dependency twolame skipped: feature twolame disabled
Dependency shine skipped: feature shine disabled
Run-time dependency libmpdclient found: YES 2.16
Configuring config.h using configuration
Program sphinx-build found: YES (/usr/bin/sphinx-build)
Build targets in project: 66
~~~

Then, with:
~~~
$ ninja -d explain -C output/release
~~~
the output is:
~~~
...
ninja: Entering directory `output/release'
ninja explain: output PHONY of phony edge with no inputs doesn't exist
ninja explain: PHONY is dirty
ninja explain: GitVersion.cxx is dirty
ninja explain: deps for 'log@sta/src_Log.cxx.o' are missing
ninja explain: log@sta/src_Log.cxx.o is dirty
ninja explain: deps for 'log@sta/src_LogBackend.cxx.o' are missing
ninja explain: log@sta/src_LogBackend.cxx.o is dirty
ninja explain: liblog.a is dirty
ninja explain: deps for 'src/util/ed6d25d@@util@sta/Exception.cxx.o' are missing
ninja explain: src/util/ed6d25d@@util@sta/Exception.cxx.o is dirty
ninja explain: deps for 'src/util/ed6d25d@@util@sta/Alloc.cxx.o' are missing
...
    a lot of similiar^ messages 
...
ninja explain: libbasic.a is dirty
ninja explain: src/config/libfs.a is dirty
ninja explain: liblog.a is dirty
ninja explain: src/fs/libfs.a is dirty
ninja explain: src/lib/zlib/libzlib.a is dirty
ninja explain: src/system/libsystem.a is dirty
ninja explain: src/lib/icu/libicu.a is dirty
ninja explain: src/util/libutil.a is dirty
ninja explain: src/lib/dbus/libdbus.a is dirty
ninja explain: src/event/libevent.a is dirty
ninja explain: src/thread/libthread.a is dirty
ninja explain: src/net/libnet.a is dirty
ninja explain: src/neighbor/libneighbor_glue.a is dirty
ninja explain: src/neighbor/plugins/libneighbor_plugins.a is dirty
...
    a lot of similiar^ messages 
...
ninja explain: mpd is dirty
ninja explain: output doc/html doesn't exist
ninja explain: doc/html is dirty
[620/621] Generating HTML documentation with a custom command
/media/SOFTWARE/BUILDS/amd64/mpd/mpd-0.21.21-cfa4524/mpd-0.21.21/doc/plugins.rst:2: WARNING: Duplicate explicit target name: "more information".
/media/SOFTWARE/BUILDS/amd64/mpd/mpd-0.21.21-cfa4524/mpd-0.21.21/doc/user.rst:1071: WARNING: unknown option: --verbose
/media/SOFTWARE/BUILDS/amd64/mpd/mpd-0.21.21-cfa4524/mpd-0.21.21/doc/user.rst:1132: WARNING: unknown option: --verbose
WARNING: html_static_path entry '/media/SOFTWARE/BUILDS/amd64/mpd/mpd-0.21.21-cfa4524/mpd-0.21.21/doc/_static' does not exist
[621/621] Linking target mpd
~~~

Then:
~~~
ninja -d explain -C output/release install
~~~
fails:
~~~
ninja: Entering directory `output/release'
ninja explain: PHONY is dirty
ninja explain: PHONY is dirty
ninja explain: GitVersion.cxx is dirty
ninja explain: GitVersion.cxx is dirty
ninja explain: GitVersion.cxx is dirty
ninja explain: mpd@exe/meson-generated_.._GitVersion.cxx.o is dirty
ninja explain: mpd is dirty
ninja explain: all is dirty
ninja explain: meson-install is dirty
[1/2] Installing files.
Installing mpd to /usr/bin
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 131, in run
    return options.run_func(options)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 538, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 358, in do_install
    self.install_targets(d)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 466, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(d.dirmaker, outdir))
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 273, in do_copyfile
    shutil.copystat(from_file, to_file)
  File "/usr/lib/python3.7/shutil.py", line 205, in copystat
    follow_symlinks=follow)
FileNotFoundError: [Errno 2] No such file or directory
FAILED: meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
~~~

Regards

**Comment by MaxKellermann** [comment]
This is a Meson crash, and that shouldn't happen. Maybe MPD's meson configuration is buggy as well, but we don't know until this Meson bug is fixed (so Meson emits a proper error message instead of crashing).
